### ISSUE TITLE
How to run SQL after startup?  

### ISSUE THREAD

**Issue by martinthurn** [kartoza/docker-postgis#100]
When loading "mainstream" postgres containers via the docker-maven-plugin, we can put SQL files in /docker-entrypoint-initdb.d and they will run after startup.  How can we achieve that with your postgis container?  How can we create tables and insert data after startup?

**Comment by NyakudyaA** [comment]
@martinthurn When you spin a container you can basically run any scripts again the database. 
```
docker run --name "postgis" -p 25432:5432 -d -t kartoza/postgis
psql -d gis -p 25432 -h localhost -u Username -f database.sql
```
Is there any reason why you would prefer the scripts to be incorporated into the image?

**Comment by martinthurn** [comment]
I'm using the docker-maven-plugin and we don't have access to the command line.

**Comment by timlinux** [comment]
@martinthurn we would need to add some configuration options to support that, currently it is not supported in our build.

**Comment by Ricardo-C-Oliveira** [comment]
Is this still unsupported? We are looking to pack the data with the image. Right now when I use:
```
volumes:
      - ./database/databases/create_database.psql:/docker-entrypoint-initdb.d/1-create_database.psql
      - ./database/schemas/load_schemas.psql:/docker-entrypoint-initdb.d/1-load_schemas.psql
```

I get: 

```
postgres_1  | 2018-11-08 19:16:25.094 UTC [23] LOG:  received smart shutdown request
postgres_1  | 2018-11-08 19:16:25.095 UTC [34] LOG:  autovacuum launcher shutting down
postgres_1  | 2018-11-08 19:16:25.099 UTC [30] LOG:  shutting down
postgres_1  | 2018-11-08 19:16:25.121 UTC [23] LOG:  database system is shut down
postgres_1  |
postgres_1  | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/1-create_database.psql
postgres_1  |
postgres_1  | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/1-load_schemas.psql
postgres_1  |
postgres_1  | Postgres initialisation process completed .... restarting in foreground
postgres_1  | 2018-11-08 19:16:26.149 UTC [205] LOG:  database system was shut down at 2018-11-08 19:16:25 UTC
postgres_1  | 2018-11-08 19:16:26.152 UTC [205] LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | 2018-11-08 19:16:26.155 UTC [202] LOG:  database system is ready to accept connections
postgres_1  | 2018-11-08 19:16:26.158 UTC [209] LOG:  autovacuum launcher started
```

So the database is shutdown before the init scripts can run, is there any way around this?

**Comment by NyakudyaA** [comment]
@livemixlove I will investigate this and add these options

**Comment by thnkloud9** [comment]
any updates on this issue?

**Comment by allthesignals** [comment]
I think we were going down a rabbit hole with this, following the wrong documentation [(which we assumed this extended from)](https://hub.docker.com/_/postgres/):

> If you would like to do additional initialization in an image derived from this one, add one or more *.sql, *.sql.gz, or *.sh scripts under /docker-entrypoint-initdb.d (creating the directory if necessary). After the entrypoint calls initdb to create the default postgres user and database, it will run any *.sql files, run any executable *.sh scripts, and source any non-executable *.sh scripts found in that directory to do further initialization before starting the service.

I think in some form, the script is run, but:
 - `*.sql` scripts silently fail
 - `*.sh` scripts that use the documented approach to connecting via `psql` cannot connect

We are looking for other approaches, but it's good to understand that this image does not necessarily extend other postgres "core" images.

**Comment by allthesignals** [comment]
I think we were going down a rabbit hole with this, following the wrong documentation [(which we assumed this extended from)](https://hub.docker.com/_/postgres/):

> If you would like to do additional initialization in an image derived from this one, add one or more *.sql, *.sql.gz, or *.sh scripts under /docker-entrypoint-initdb.d (creating the directory if necessary). After the entrypoint calls initdb to create the default postgres user and database, it will run any *.sql files, run any executable *.sh scripts, and source any non-executable *.sh scripts found in that directory to do further initialization before starting the service.

I think in some form, the script is run, but:
 - `*.sql` scripts silently fail
 - `*.sh` scripts that use the documented approach to connecting via `psql` cannot connect

We are looking for other approaches, but it's good to understand that this image does not necessarily extend other postgres "core" images.

**Comment by NyakudyaA** [comment]
@allthesignals can you please test the work I have been doing here and revert to me if it works seamlessly
https://github.com/NyakudyaA/docker-postgis/tree/fix-startup-scripts

**Comment by NyakudyaA** [comment]
Merged in develop
