### ISSUE TITLE
raster2pgsql support?

### ISSUE THREAD

**Issue by alex-l-kong** [kartoza/docker-postgis#102]
I'm trying to use raster2pgsql to import a few .adf files into PostGIS using this container. I tried using docker exec -it <CONTAINER ID> /bin/bash raster2pgsql ..., but that hasn't worked. Is there a way I can use raster2pgsql with this container?

**Comment by timlinux** [comment]
@NyakudyaA can you help with this?

**Comment by NyakudyaA** [comment]
@alex-l-kong I have got PostGIS installed natively on my ubuntu and I can run the following:
`docker exec -it postgis  /usr/bin/raster2pgsql  -G` 
Alternatively, you should be able to exec into the container and do 'apt-get install -y postgis` which will install all the utilities like shp2pgsql and raster2pgsql

**Comment by A108669** [comment]
@NyakudyaA : Will running `apt-get install -y postgis` not interfere with the installation of postgis in the Dockerfile?

**Comment by NyakudyaA** [comment]
> @NyakudyaA : Will running `apt-get install -y postgis` not interfere with the installation of postgis in the Dockerfile?
> 
> Correct me if I'm wrong the Dockerfile installs postgis 2.5, but I believe the version in apt-get isn't the most recent?
> 
> EDIT:
> 
> This did the trick for me. Thanks!

@A108669 glad it worked. You could also just create a new Dockerfile and just run
```
FROM kartoza/postgis:11.0-2.5
RUN apt-get install -y postgis
```
