### ISSUE TITLE
Default locale SQL-ASCII?

### ISSUE THREAD

**Issue by maratumba** [kartoza/docker-postgis#104]
I'm getting a SQL-ASCII charset when I run a container.

```
 The database cluster will be initialized with locale "C".
 The default database encoding has accordingly been set to "SQL_ASCII".
 The default text search configuration will be set to "english".
```

But in this [tutorial](https://alexurquhart.com/post/set-up-postgis-with-docker/), the default locale seems to be UTF8, which is what I need. Is there a way to change the default locale when running the container for the first time?

**Comment by NyakudyaA** [comment]
@maratumba we could just add an environment variable that sets the encoding using
`PGCLIENTENCODING=LATIN1`

**Comment by maratumba** [comment]
I forked the project and found a solution (for Turkish at least). It was a bit more work than a single environment variable as I remember. Need to do some work to make it so.

**Comment by billtian** [comment]
@maratumba could you show your solution here ? i found that the encoding is utf-8 if run docker derectly without the `-v` parameter .

**Comment by maratumba** [comment]
My solution is in the pull request #105. It's been a long time since I built the image, it might have been that it was an older version.

**Comment by NyakudyaA** [comment]
@maratumba Do you have any plans to fix the issues commented in the PR  so that we can merge the PR

**Comment by maratumba** [comment]
That's on my mind for a long time now. My MacOS version doesn't seem to get along with Docker so I gave up on reinstalling it every few days. I'll try to find some time to try to fix the issues on my DO server.

**Comment by NyakudyaA** [comment]
This has been addressed in the PR https://github.com/kartoza/docker-postgis/pull/144
