### ISSUE TITLE
FATAL:  data directory "/var/lib/postgresql/9.6/main" has group or world access

### ISSUE THREAD

**Issue by darkcloud1801** [kartoza/docker-postgis#108]
In OS X Mojave with the latest Docker for Mac installed, and this section of my docker-compose.yml file, I get this build error.  Any suggestions?

 db:
    image: kartoza/postgis:9.6-2.4
    container_name: sherman-postgres
    environment:
      - POSTGRES_DBNAME=strax
      - POSTGRES_USER=river
      - POSTGRES_PASS=song
      - ALLOW_IP_RANGE=0.0.0.0/0
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes/db:/var/lib/postgresql

sherman-postgres | Add rule to pg_hba: 0.0.0.0/0
sherman-postgres | Add rule to pg_hba: replication user
sherman-postgres | Setup master database
sherman-postgres | Creating Postgres data at /var/lib/postgresql/9.6/main
sherman-postgres | Initializing Postgres Database at /var/lib/postgresql/9.6/main
sherman-postgres | The files belonging to this database system will be owned by user "postgres".
sherman-postgres | This user must also own the server process.
sherman-postgres | 
sherman-postgres | The database cluster will be initialized with locale "C".
sherman-postgres | The default database encoding has accordingly been set to "SQL_ASCII".
sherman-postgres | The default text search configuration will be set to "english".
sherman-postgres | 
sherman-postgres | Data page checksums are disabled.
sherman-postgres | 
sherman-postgres | fixing permissions on existing directory /var/lib/postgresql/9.6/main ... ok
sherman-postgres | creating subdirectories ... ok
sherman-postgres | selecting default max_connections ... 100
sherman-postgres | selecting default shared_buffers ... 128MB
sherman-postgres | selecting dynamic shared memory implementation ... posix
sherman-postgres | creating configuration files ... ok
sherman-postgres | running bootstrap script ... ok
sherman-postgres | performing post-bootstrap initialization ... ok
sherman-postgres | syncing data to disk ... ok
sherman-postgres | 
sherman-postgres | Success. You can now start the database server using:
sherman-postgres | 
sherman-postgres |     /usr/lib/postgresql/9.6/bin/pg_ctl -D /var/lib/postgresql/9.6/main -l logfile start
sherman-postgres | 
sherman-postgres | 
sherman-postgres | WARNING: enabling "trust" authentication for local connections
sherman-postgres | You can change this by editing pg_hba.conf or using the option -A, or
sherman-postgres | --auth-local and --auth-host, the next time you run initdb.
sherman-postgres | 2018-11-14 04:02:28.092 UTC [42] FATAL:  data directory "/var/lib/postgresql/9.6/main" has group or world access
sherman-postgres | 2018-11-14 04:02:28.092 UTC [42] DETAIL:  Permissions should be u=rwx (0700).
sherman-postgres | psql: could not connect to server: No such file or directory
sherman-postgres | 	Is the server running locally and accepting
sherman-postgres | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by darkcloud1801** [comment]
I attempting to use a bound volume for my postgres data. 
I elected to switch over to using a regular docker volume, and the issue was resolved.

However, I think there should still be a solution with bound volumes.

**Comment by darkcloud1801** [comment]
I did, but it doesnt' resolve the issue.

**Comment by NyakudyaA** [comment]
This works on my Mac and I will close this. Feel free to open the issue again should you encounter this
