### ISSUE TITLE
Docker entrypoint initdb.d - Postgres killed after setup-database.sh

### ISSUE THREAD

**Issue by schulzsebastian** [kartoza/docker-postgis#109]
Hi!

I had problems with using /docker-entrypoint-initdb.d/* - scripts were running (not ignoring) without errors - but there was no changes on DB. I realized that setup-database.sh kills Postgres process - so that's why queries are not running on DB instance. 
I erased "killing" code from setup-database.sh and pasted after 37 line (end of /docker-entrypoint-initdb.d/* loop) in docker-entrypoint.sh and it works.

Is it a problem with docker-postgis image or my configuration?

**Comment by NyakudyaA** [comment]
@schulzsebastian I think this issue is related to https://github.com/kartoza/docker-postgis/issues/100
I will investigate this and tackle it

**Comment by NyakudyaA** [comment]
@schulzsebastian  https://github.com/NyakudyaA/docker-postgis/tree/fix-startup-scripts
please test the above

**Comment by NyakudyaA** [comment]
Now merged in develop
