### ISSUE TITLE
streaming replication not running

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-postgis#112]
# problem

after a successful base backup on a slave, setting 'destroy on restart' to False and restarting, replication does not take place (no wal_receiver process and no changes from master are visible in the slave db)

as I write, gisbox2 is exhibiting this behaviour and is the most urgent to get working

# solution

troubleshoot and fix

**Comment by NyakudyaA** [comment]
@gubuntu can we close this ?

**Comment by gubuntu** [comment]
yes, working fine
