### ISSUE TITLE
Attempts to create a database when one exists already

### ISSUE THREAD

**Issue by evgeny29** [kartoza/docker-postgis#125]
When multiple databases are created and user matches a name of one of them, restarting a container fails as it attempts to create a database again as `psql -l | grep -w ${db} | wc -l` returns a non '1' value.
https://github.com/kartoza/docker-postgis/blob/21b45fcabde9047430d21e88723fb50a449fa5c3/setup-database.sh#L51

Example:
POSTGRES_USER=dbname1
POSTGRES_DBNAME=dbname1,dbname2

`psql -l | grep -w ${db} | wc -l`
2

**Comment by NyakudyaA** [comment]
@evgeny29 I will take a look at it

**Comment by evgeny29** [comment]
@NyakudyaA it is not a password, but a username.

**Comment by evgeny29** [comment]
Please consider using something like below to prevent other unwanted matches..
Also note `-eq 0` for comparison.

```
RESULT=`su - postgres -c "psql -t -c \"SELECT count(1) from pg_database where datname='${db}';\""`
if [[ ${RESULT} -eq 0 ]]; then
```

**Comment by NyakudyaA** [comment]
> Please consider using something like below to prevent other unwanted matches..
> Also note `-eq 0` for comparison.
> 
> ```
> RESULT=`su - postgres -c "psql -t -c \"SELECT count(1) from pg_database where datname='${db}';\""`
> if [[ ${RESULT} -eq 0 ]]; then
> ```

@evgeny29 note the changes in the PR.
https://github.com/NyakudyaA/docker-postgis/blob/startup-scripts/setup-database.sh#L52

**Comment by evgeny29** [comment]
@NyakudyaA 
The current logic uses grep on "psql -l" results which may result in unwanted matches, eg if a user names his database C, SQL_ASCII or CTc as these strings appear in the Collate, Encoding,Access privileges columns.
Also, $RESULT is numeric and ` == '0' ` will be false, I think we need to use `-eq` operator.

**Comment by NyakudyaA** [comment]
> @NyakudyaA
> The current logic uses grep on "psql -l" results which may result in unwanted matches, eg if a user names his database C, SQL_ASCII or CTc as these strings appear in the Collate, Encoding,Access privileges columns.
> Also, $RESULT is numeric and `== '0'` will be false, I think we need to use `-eq` operator.

@evgeny29 Thanks a lot for your inputs. I have changed the PR to include your changes
