### ISSUE TITLE
Question about heavy load database

### ISSUE THREAD

**Issue by elgerm** [kartoza/docker-postgis#132]
Hi, 

Thanks for the really handy postgis image. I've been using it for development for quite a while now. I'm going to put it in production soon and am thinking about just using this docker image for it. The opening text of the readme states: 'though probably not for heavy load databases'. - what do you mean by this? It's just postgresql right? I know I will have to fine tune the postgresql.conf, but other than that, what is holding this image back from being a heavy load production db?

I realize this might be a broad question (performance tuning), but I just want to know what in particular this image has that you're not sure about regarding performance.

--Elger

**Comment by NyakudyaA** [comment]
@elgerm The image can be used as is in production environments. The statement meant there are other optimisations you can do ie using load balancers. We have also customised the conf files with some setting which improve performance. I will reword the readme. Perhaps it would be nice for you to benchmark the performance once you have it running in production and give us feedback. 

Please look at the optimisations for the conf file here https://github.com/kartoza/docker-postgis/blob/develop/setup-conf.sh#L15

**Comment by elgerm** [comment]
@NyakudyaA Thanks for the reply and the config. I will try and set it up with replication together with docker swarm. There will be quite some load (5000+ concurrent users / 200gb db) and coming from sql server it will be interesting to say the least.  I certainly will benchmark and give feedback about tweaks I'm sure I will stumble upon.
