### ISSUE TITLE
Please add OGR FDW

### ISSUE THREAD

**Issue by timlinux** [kartoza/docker-postgis#139]
Hi @NyakudyaA 

Can you test out adding the OGR FDW to the build?

https://packages.debian.org/buster/postgresql-11-ogr-fdw

That will let us mount GIS  files into the container and treat them as FDW's.

Thanks!

**Comment by NyakudyaA** [comment]
@timlinux 
I have added this and tested
![fdw-add](https://user-images.githubusercontent.com/2510900/62115400-a98fa200-b2b8-11e9-9cf7-36dfa1ddfca8.png)
