### ISSUE TITLE
Fatal error when mounting dir that is not in current working dir

### ISSUE THREAD

**Issue by thacoon** [kartoza/docker-postgis#145]
Hi,
 I have a really weird issue. I created a postgis dir on my host system `mkdir -p /opt/postgres_data`.

So when running `cd /opt && docker run -d -v postgres_data:/var/lib/postgresql kartoza/postgis` everything works fine.

But when I run `docker run -d -v /opt/postgres_data:/var/lib/postgresql kartoza/postgis` I get a fatal error: `FATAL:  "min_wal_size" must be at least twice "wal_segment_size"` and the database system is shut down.

However using another postgis docker image and running `docker run -d -v /opt/postgres_data:/var/lib/postgresql mdillon/postgis` everything works.

Running a `Linux mvp1 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linu`

This also means I cannot run this container with docker-compose as this would require defining an absolute path.

**Comment by NyakudyaA** [comment]
@thacoon I think the issue might have been introduced by the `--wal-segsize` which is now configurable on the setup of the cluster as described here https://www.enterprisedb.com/edb-docs/d/edb-postgres-advanced-server/user-guides/user-guide/11/EDB_Postgres_Advanced_Server_Guide.1.046.html
Can you please try out the PR https://github.com/kartoza/docker-postgis/pull/144 as it should fix this issue you are experiencing

**Comment by NyakudyaA** [comment]
@thacoon can you please pull the latest image and test it
