### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by AlvaroLQueiroz** [kartoza/docker-postgis#149]
The docs says that the variable for set the *password* is **POSTGRES_PASS**, but apparently is wrong. In my tests, works only when i set **POSTGRES_PASSWORD**.

Another question about the variables is, why not keep the same pattern of oficial postgres image? Where to define the DB name we need set **POSTGRES_DB** and not **POSTGRES_DBNAME**.

**Comment by NyakudyaA** [comment]
> The docs says that the variable for set the _password_ is **POSTGRES_PASS**, but apparently is wrong. In my tests, works only when i set **POSTGRES_PASSWORD**.

If you use the docker-compose.yml you will realize that it uses **POSTGRES_PASS** which works
> 
> Another question about the variables is, why not keep the same pattern of oficial postgres image? Where to define the DB name we need set **POSTGRES_DB** and not **POSTGRES_DBNAME**.

the docker-compose.yml also uses **POSTGRES_DBNAME**
Please look at https://github.com/kartoza/docker-postgis/blob/develop/env-data.sh#L19

**Comment by AlvaroLQueiroz** [comment]
Sorry, my bad. I tried again more calmly and it worked perfectly.
