### ISSUE TITLE
Cannot connect to the container

### ISSUE THREAD

**Issue by volkanunsal** [kartoza/docker-postgis#15]
```bash
psql -h $(boot2docker ip) -p 25432 -d gis -U docker
```

That should work, but doesn't.

```bash
  psql: FATAL:  no pg_hba.conf entry for host "192.168.59.3", user "docker", database "gis", SSL on
  FATAL:  no pg_hba.conf entry for host "192.168.59.3", user "docker", database "gis", SSL off
```

I noticed that the database [only accept connections from Docker subnet](https://github.com/kartoza/docker-postgis/blob/develop/setup.sh#L6-L7). What does this mean for boot2docker users?

**Comment by RLovelett** [comment]
@volkanunsal did you find a work around for this?

**Comment by timlinux** [comment]
@RLovelett The work around would be to disable that rule in pg_hba or perhaps I could set a flag in env vars when running the container that disables it via a script. 

Under linux we don't get this issue because the host gets assigned an ip on the docker network via multi-homing:

```
sudo ifconfig
...
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.42.1  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::5484:7aff:fefe:9799  prefixlen 64  scopeid 0x20<link>
        ether 56:84:7a:fe:97:99  txqueuelen 0  (Ethernet)
        RX packets 18  bytes 3191 (3.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 29  bytes 4038 (3.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by fullofcaffeine** [comment]
Would wrapping it in a VBOX VM (vagrant) and mapping the ports to the host be a workaround?

**Comment by fullofcaffeine** [comment]
+1

I'm using this for now https://github.com/rogelio2k/vagrant-postgis2, but I'd really prefer to use Docker directly (also because I'm working a lot with Docker lately), so a solution/workaround to this issue would be great. I'm also on OSX (Yosemite) and have the same issue as the OP.

**Comment by volkanunsal** [comment]
I think I solved this by changing the pg_hba.conf to accept connections from anywhere.

**Comment by fullofcaffeine** [comment]
@volkanunsal Thanks for the tip!
