### ISSUE TITLE
SSL ERROR:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by malone081021** [kartoza/docker-postgis#151]
run such commad:
```
sudo docker run --name "postgis" -p 25432:5432 -d -t kartoza/postgis -e ALLOW_IP_RANGE="0.0.0.0/0" -e IP_LIST="222.128.44.115"
```
connect to db , get flowing error:
![image](https://user-images.githubusercontent.com/43690259/65488603-1485df80-dedc-11e9-9445-531981aab0a9.png)

**Comment by NyakudyaA** [comment]
hi @malone081021 I suggest if you are setting of `IP_LIST="222.128.44.115"` to also properly configure `ALLOW_IP_RANGE="0.0.0.0/0"` to listen to a few IP addresses as opposed to all.

Let me know if it works

**Comment by malone081021** [comment]
you mean 
```
sudo docker run --name "postgis" -p 25432:5432 -d -t kartoza/postgis -e ALLOW_IP_RANGE="222.128.44.115/32" -e IP_LIST="222.128.44.115"
```

it is not works @NyakudyaA

**Comment by NyakudyaA** [comment]
@malone081021 Does it work or not. Please close issue if it works or send logs again if it still doesnt

**Comment by malone081021** [comment]
```sudo docker run --name "postgis" -p 25432:5432 -d -t kartoza/postgis -e ALLOW_IP_RANGE="222.128.44.115/32" -e IP_LIST="222.128.44.115"```

it  does not work

![image](https://user-images.githubusercontent.com/43690259/65754216-22896980-e143-11e9-8ba3-784bb7adc633.png)
@NyakudyaA

**Comment by NyakudyaA** [comment]
@malone081021 cannot replicate with databases running on a separate host. please reopen if the issue persist. Try to use the latest image postgis:12.0
