### ISSUE TITLE
Unable to start postgis: psql connection errors

### ISSUE THREAD

**Issue by oguya** [kartoza/docker-postgis#152]
Greetings!  Thanks a lot for this postgis docker image. It has served us well for sometime.

Unfortunately, recently, we've been getting `psql: could not connect to server: No such file or directory` errors on startup.

This setup used to work well several months ago, but now it doesn't, throws the same `psql` errors on startup:

```
db:
  image: kartoza/postgis:9.6-2.4
  environment:
    - POSTGRES_DB=postgis
    - POSTGRES_PASSWORD=strong-pass-here
    - POSTGRES_USER=postgres
  volumes:
    - .postgres_data/:/var/lib/postgresql:rw
  ports:
    - 5432
```

I've also tried using the latest stable image as stated in this[[1](https://github.com/kartoza/docker-postgis/blob/master/docker-compose.yml)] docker-compose example, but it fails with the same error:

```
db_1         | Add rule to pg_hba: 0.0.0.0/0
db_1         | Add rule to pg_hba: replication user
db_1         | Setup master database
db_1         | Creating Wal archive directory at /opt/archivedir
db_1         | psql: could not connect to server: No such file or directory
db_1         |  Is the server running locally and accepting
db_1         |  connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
db_1         | 2019-10-07 03:23:41.565 UTC [19] FATAL:  could not map anonymous shared memory: Cannot allocate memory
db_1         | 2019-10-07 03:23:41.565 UTC [19] HINT:  This error usually means that PostgreSQL's request for a shared memory segment exceeded available memo$
y, swap space, or huge pages. To reduce the request size (currently 545611776 bytes), reduce PostgreSQL's shared memory usage, perhaps by reducing shared_buf$
ers or max_connections.
db_1         | 2019-10-07 03:23:41.565 UTC [19] LOG:  database system is shut down
db_1         | psql: could not connect to server: No such file or directory
db_1         |  Is the server running locally and accepting
db_1         |  connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
db_1         | psql: could not connect to server: No such file or directory
db_1         |  Is the server running locally and accepting
```

Could I be missing something that is not stated in the example `docker-compose.yml` file?

1. https://github.com/kartoza/docker-postgis/blob/master/docker-compose.yml

**Comment by NyakudyaA** [comment]
Are you using a docker volume or host mounted data directory?

I can run the setup fine on my machine without any hassles
![Screenshot 2019-10-07 at 08 24 29](https://user-images.githubusercontent.com/2510900/66289211-46d00d80-e8dc-11e9-8368-a8add0f18acd.png)

![Screenshot 2019-10-07 at 08 25 01](https://user-images.githubusercontent.com/2510900/66289219-4df71b80-e8dc-11e9-8100-4e34a156e032.png)

**Comment by oguya** [comment]
Though, I'm using host mounted data directories for easier backups.

I've realised when one instance(docker-compose) of postgis container is running on a different directory, I can nolonger get another one in a different directory to run, all on the same host:

- 1st instance - docker-compose stack:
  - `docker-compose.yml` on `pg-a/` dir.

        $ cat /tmp/pg-a/docker-compose.yml
        version: '3'
        volumes:
          postgis-data:
        services:
         db:
           restart: unless-stopped
           image: kartoza/postgis:9.6-2.4
           environment:
             - POSTGRES_DB=gis
             - POSTGRES_PASSWORD=docker
             - POSTGRES_USER=docker
             - ALLOW_IP_RANGE=0.0.0.0/0
           volumes:
             - .postgres_data/:/var/lib/postgresql:rw
           ports:
             - 5432

  - docker-compose  startup

        # docker-compose up
        Creating network "pg-a_default" with the default driver
        Creating volume "pg-a_postgis-data" with default driver
        Creating pg-a_db_1 ... done
        Attaching to pg-a_db_1
        db_1  |
        db_1  | ssl already configured
        db_1  | we will setup pg_hba conf
        db_1  | Add rule to pg_hba: 0.0.0.0/0
        db_1  | Add rule to pg_hba: replication user
        db_1  | Setup master database
        db_1  | Creating Postgres data at /var/lib/postgresql/9.6/main
        db_1  | Creating Wal archive directory at /opt/archivedir
        db_1  | Initializing Postgres Database at /var/lib/postgresql/9.6/main
        db_1  | The files belonging to this database system will be owned by user "postgres".
        db_1  | This user must also own the server process.
        db_1  |
        db_1  | The database cluster will be initialized with locale "C".
        db_1  | The default database encoding has accordingly been set to "SQL_ASCII".
        db_1  | The default text search configuration will be set to "english".
        db_1  |
        db_1  | Data page checksums are disabled.
        db_1  |
        db_1  | fixing permissions on existing directory /var/lib/postgresql/9.6/main ... ok
        db_1  | creating subdirectories ... ok
        db_1  | selecting default max_connections ... 100
        db_1  | selecting default shared_buffers ... 128MB
        db_1  | selecting dynamic shared memory implementation ... posix
        db_1  | creating configuration files ... ok
        db_1  | running bootstrap script ... ok
        db_1  | performing post-bootstrap initialization ... ok
        db_1  | syncing data to disk ... ok
        db_1  |
        db_1  | Success. You can now start the database server using:
        db_1  |
        db_1  |     /usr/lib/postgresql/9.6/bin/pg_ctl -D /var/lib/postgresql/9.6/main -l logfile start
        db_1  |
        db_1  |
        db_1  | WARNING: enabling "trust" authentication for local connections
                   
        db_1  | You can change this by editing pg_hba.conf or using the option -A, or
        db_1  | --auth-local and --auth-host, the next time you run initdb.
        db_1  | 2019-10-07 09:15:34.331 UTC [41] LOG:  database system was shut down at 2019-10-07 09:15:34 UTC
        db_1  | 2019-10-07 09:15:34.333 UTC [41] LOG:  MultiXact member wraparound protections are now enabled
        db_1  | 2019-10-07 09:15:34.337 UTC [36] LOG:  database system is ready to accept connections
        db_1  | 2019-10-07 09:15:34.339 UTC [45] LOG:  autovacuum launcher started
        db_1  |                              List of databases
        db_1  |    Name    |  Owner   | Encoding  | Collate | Ctype |   Access privileges
        db_1  | -----------+----------+-----------+---------+-------+-----------------------
        db_1  |  postgres  | postgres | SQL_ASCII | C       | C     |
        db_1  |  template0 | postgres | SQL_ASCII | C       | C     | =c/postgres          +
        db_1  |            |          |           |         |       | postgres=CTc/postgres
        db_1  |  template1 | postgres | SQL_ASCII | C       | C     | =c/postgres          +
        db_1  |            |          |           |         |       | postgres=CTc/postgres
        db_1  | (3 rows)
        db_1  |
        db_1  | postgres ready
        db_1  | Postgis is missing, installing now
        db_1  | Creating template postgis
        db_1  | Enabling template_postgis as a template
        db_1  | UPDATE 1
        db_1  | Loading postgis extension
        db_1  | CREATE EXTENSION
        db_1  | Enabling hstore in the template
        db_1  | CREATE EXTENSION
        db_1  | Enabling topology in the template
        db_1  | CREATE EXTENSION
        db_1  | Loading legacy sql
        db_1  | /usr/share/postgresql/9.6/contrib/postgis-2.4/legacy_minimal.sql: No such file or directory
        db_1  | /usr/share/postgresql/9.6/contrib/postgis-2.4/legacy_gist.sql: No such file or directory
        db_1  | Setup postgres User:Password
        db_1  | CREATE ROLE
        db_1  | Check default db exists
        db_1  | Create default db gis
        db_1  |                                  List of databases
        db_1  |        Name       |  Owner   | Encoding  | Collate | Ctype |   Access privileges
        db_1  | ------------------+----------+-----------+---------+-------+-----------------------
        db_1  |  gis              | docker   | UTF8      | C       | C     |
        db_1  |  postgres         | postgres | SQL_ASCII | C       | C     |
        db_1  |  template0        | postgres | SQL_ASCII | C       | C     | =c/postgres          +
        db_1  |                   |          |           |         |       | postgres=CTc/postgres
        db_1  |  template1        | postgres | SQL_ASCII | C       | C     | =c/postgres          +
        db_1  |                   |          |           |         |       | postgres=CTc/postgres
        db_1  |  template_postgis | postgres | UTF8      | C       | C     |
        db_1  | (5 rows)
        db_1  |
        db_1  | 2019-10-07 09:15:40.760 UTC [36] LOG:  received smart shutdown request
        db_1  | 2019-10-07 09:15:40.763 UTC [45] LOG:  autovacuum launcher shutting down
        db_1  | 2019-10-07 09:15:40.771 UTC [42] LOG:  shutting down
        db_1  | 2019-10-07 09:15:40.812 UTC [36] LOG:  database system is shut down
        db_1  |
        db_1  | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
        db_1  |
        db_1  | Postgres initialisation process completed .... restarting in foreground
        db_1  | 2019-10-07 09:15:41.962 UTC [218] LOG:  database system was shut down at 2019-10-07 09:15:40 UTC
        db_1  | 2019-10-07 09:15:41.977 UTC [218] LOG:  MultiXact member wraparound protections are now enabled
        db_1  | 2019-10-07 09:15:41.989 UTC [215] LOG:  database system is ready to accept connections
        db_1  | 2019-10-07 09:15:41.992 UTC [222] LOG:  autovacuum launcher started


- 2nd instance - docker-compose stack:
  - `docker-compose.yml` on `pg-b/` dir.

        $ cat /tmp/pg-b/docker-compose.yml
        version: '3'
        volumes:
          postgis-data:
        services:
         db:
           restart: unless-stopped
           image: kartoza/postgis:9.6-2.4
           environment:
             - POSTGRES_DB=gis
             - POSTGRES_PASSWORD=docker
             - POSTGRES_USER=docker
             - ALLOW_IP_RANGE=0.0.0.0/0
           volumes:
             - .postgres_data/:/var/lib/postgresql:rw
           ports:
             - 5432

  - docker-compose  startup

        # docker-compose up
        Creating network "pg-b_default" with the default driver
        Creating volume "pg-b_postgis-data" with default driver
        Creating pg-b_db_1 ... done
        Attaching to pg-b_db_1
        db_1  |
        db_1  | ssl already configured
        db_1  | we will setup pg_hba conf
        db_1  | Add rule to pg_hba: 0.0.0.0/0
        db_1  | Add rule to pg_hba: replication user
        db_1  | Setup master database
        db_1  | Creating Postgres data at /var/lib/postgresql/9.6/main
        db_1  | Creating Wal archive directory at /opt/archivedir
        db_1  | Initializing Postgres Database at /var/lib/postgresql/9.6/main
        db_1  | The files belonging to this database system will be owned by user "postgres".
        db_1  | This user must also own the server process.
        db_1  |
        db_1  | The database cluster will be initialized with locale "C".
        db_1  | The default database encoding has accordingly been set to "SQL_ASCII".
        db_1  | The default text search configuration will be set to "english".
        db_1  |
        db_1  | Data page checksums are disabled.
        db_1  |
        db_1  | fixing permissions on existing directory /var/lib/postgresql/9.6/main ... ok
        db_1  | creating subdirectories ... ok
        db_1  | selecting default max_connections ... 100
        db_1  | selecting default shared_buffers ... 128MB
        db_1  | selecting dynamic shared memory implementation ... posix
        db_1  | creating configuration files ... ok
        db_1  | running bootstrap script ... ok
        db_1  | performing post-bootstrap initialization ... ok
        db_1  | syncing data to disk ... ok
        db_1  |
        db_1  | WARNING: enabling "trust" authentication for local connections
        db_1  | You can change this by editing pg_hba.conf or using the option -A, or
        db_1  | --auth-local and --auth-host, the next time you run initdb.
        db_1  |
        db_1  | Success. You can now start the database server using:
        db_1  |
        db_1  |     /usr/lib/postgresql/9.6/bin/pg_ctl -D /var/lib/postgresql/9.6/main -l logfile start
        db_1  | 2019-10-07 09:16:23.977 UTC [36] FATAL:  could not map anonymous shared memory: Cannot allocate memory
        db_1  | 2019-10-07 09:16:23.977 UTC [36] HINT:  This error usually means that PostgreSQL's request for a shared memory segment exceeded available memory, swap
         space, or huge pages. To reduce the request size (currently 545611776 bytes), reduce PostgreSQL's shared memory usage, perhaps by reducing shared_buffers or
        max_connections.
        db_1  | 2019-10-07 09:16:23.978 UTC [36] LOG:  database system is shut down
        db_1  | psql: could not connect to server: No such file or directory
        db_1  |         Is the server running locally and accepting
        db_1  |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
        db_1  | psql: could not connect to server: No such file or directory
        db_1  |         Is the server running locally and accepting
        db_1  |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
        db_1  | psql: could not connect to server: No such file or directory
        db_1  |         Is the server running locally and accepting
        db_1  |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
        db_1  | psql: could not connect to server: No such file or directory
        db_1  |         Is the server running locally and accepting
        db_1  |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
        ^CGracefully stopping... (press Ctrl+C again to force)
        Stopping pg-b_db_1 ... done

**Comment by NyakudyaA** [comment]
Please try to migrate to the stable recent version of postgis which is 12.0
