### ISSUE TITLE
Support for pgrouting 3.0.0

### ISSUE THREAD

**Issue by wg-mblazin** [kartoza/docker-postgis#154]
We are trying to achieve faster results for large graphs, so we are trying to use Contraction Hierachies from pgrouting. However they were only added in pgrouting 3.0.0, any chance of supporting this version ( I think latest supported is 2.6.0 at this moment)?

**Comment by NyakudyaA** [comment]
@wg-mblazin I do not think pgRouting 3 has been released yet. There is a beta version that is still being tested. As soon as it gets released we will include it with the kartoza/postgis:12.0 image we have just released. 

You can clone the repo and check out the branch v12 and add instructions on how to compile pgRouting
https://docs.pgrouting.org/latest/en/pgRouting-installation.html#short-version

**Comment by wg-mblazin** [comment]
Yes you are right, I will wait for the official release then, seems like a lot of work to compile it myself. Looking forward to the CH feature.

**Comment by NyakudyaA** [comment]
@wg-mblazin if you are really desperate for it you can just modify the  kartoza/postgis:12.0 by running the following bash script 

```
docker run --name "postgis" -p 25432:5432 -d -t kartoza/postgis:12.0 
docker exec -it postgis bash
```
Then execute the following
```
#!/bin/bash

apt-get -y update && apt-get install -y postgresql-server-dev-12 cmake build-essential g++ libboost-graph-dev zip
wget -O pgrouting.zip https://codeload.github.com/pgRouting/pgrouting/zip/v3.0.0-beta
unzip pgrouting.zip
cd pgrouting-3.0.0-beta && mkdir build && cd build && cmake  ../ && make -j 4 && make install
```
