### ISSUE TITLE
column proisagg does not exist

### ISSUE THREAD

**Issue by rmmariano** [kartoza/docker-postgis#155]
I tried to create a PostGIS database using 9.3-2.1, 11.0-2.5 and 12.0 tags, however I'm getting the following error when I try to open 'public' schema on pgAdmin III: 

```
An error has occurred:

11:43:59: Error: ERROR:  column "proisagg" does not exist
LINE 9:  WHERE proisagg = FALSE AND pronamespace = 2200::oid
HINT:  Perhaps you meant to reference the column "pr.prolang".

An error has occurred:

11:46:24: Error: ERROR:  column rel.relhasoids does not exist
LINE 1: ...t_userbyid(rel.relowner) AS relowner, rel.relacl, rel.relhas...
```

I don't know why it is happening and how should I fix it.

I described the question on DBA StackExchange [here](https://dba.stackexchange.com/q/251796/181099).

I believe it is needed to change the definition of the query, like it was pointed [here](https://dba.stackexchange.com/a/238906/181099) and [here](https://sourceforge.net/p/phppgadmin/bugs/469/#cb6d), but I don't know how should I do that.

Would you know if Postgres of PostGIS image on Docker hub is outdated?

Thank you in advance.

**Comment by NyakudyaA** [comment]
Please upgrade to use pgadmin 4. This is not an issue with the docker container by rather a version issue with pgadmin3. I am sure when you open pgadmin3 for the first time it gives you a notification telling you which database is supported

**Comment by rmmariano** [comment]
Thank you NyakudyaA. Now I've understood the problem.
