### ISSUE TITLE
pgrouting missing in 12.0 branch

### ISSUE THREAD

**Issue by nilsnolde** [kartoza/docker-postgis#166]
pgrouting doesn't get installed anymore in the Dockerfile. Is that intentional or an accident? Else I'd PR it in.

**Comment by nilsnolde** [comment]
Just seeing #154. It's officially released by now. So it's safe to integrate, right?

**Comment by NyakudyaA** [comment]
hi @nilsnolde Has pgrouting3 been officially released ?. If so you can PR it. last time I checked it was still beta

**Comment by nilsnolde** [comment]
Hmpf, sorry @NyakudyaA, I better google that before.. Well, it's one step closer in `rc1` state, but you're right, apparently still not 1000% released. What do you think?

https://github.com/pgRouting/pgrouting/releases/
https://packages.debian.org/sid/main/postgresql-12-pgrouting

**Comment by NyakudyaA** [comment]
> Hmpf, sorry @NyakudyaA, I better google that before.. Well, it's one step closer in `rc1` state, but you're right, apparently still not 1000% released. What do you think?
> 
> https://github.com/pgRouting/pgrouting/releases/
> https://packages.debian.org/sid/main/postgresql-12-pgrouting

I think we can go ahead and install if it's already in package manager

**Comment by nilsnolde** [comment]
Nice, thx. I'll PR.

**Comment by NyakudyaA** [comment]
All done
