### ISSUE TITLE
docker-entrypoint.sh missing initdb for multiple databases

### ISSUE THREAD

**Issue by schulzsebastian** [kartoza/docker-postgis#168]
Hey guys, you're doing a great job!

I've got a question about docker-entrypoint.sh file - what is the reason for the variable SINGLE_DB? Is something preventing from initializing all databases? I've done this workaround and I don't see any problems in my project (from 26th line of docker-entrypoint.sh):

```bash
if find "/docker-entrypoint-initdb.d" -mindepth 1 -print -quit 2>/dev/null | grep -q .; then
        for f in /docker-entrypoint-initdb.d/*; do
        export PGPASSWORD=${POSTGRES_PASS}
        list=(`echo ${POSTGRES_DBNAME} | tr ',' ' '`)
        for db in "${list[@]}"
        do
            :
            case "$f" in
                *.sql)    echo "$0: running $db $f"; psql ${db} -U ${POSTGRES_USER} -p 5432 -h localhost  -f ${f} || true ;;
                *.sql.gz) echo "$0: running $db $f"; gunzip < "$f" | psql ${db} -U ${POSTGRES_USER} -p 5432 -h localhost || true ;;
                *)        echo "$0: ignoring $db $f" ;;
            esac
            echo
        done;
        done;
        # Put lock file to make sure entry point scripts were run
        touch ${SETUP_LOCKFILE}
    else
        return 0
    fi
```

**Comment by NyakudyaA** [comment]
> Hey guys, you're doing a great job!
> 
> I've got a question about docker-entrypoint.sh file - what is the reason for the variable SINGLE_DB? Is something preventing from initializing all databases? I've done this workaround and I don't see any problems in my project (from 26th line of docker-entrypoint.sh):
> 
> ```shell
> if find "/docker-entrypoint-initdb.d" -mindepth 1 -print -quit 2>/dev/null | grep -q .; then
>         for f in /docker-entrypoint-initdb.d/*; do
>         export PGPASSWORD=${POSTGRES_PASS}
>         list=(`echo ${POSTGRES_DBNAME} | tr ',' ' '`)
>         for db in "${list[@]}"
>         do
>             :
>             case "$f" in
>                 *.sql)    echo "$0: running $db $f"; psql ${db} -U ${POSTGRES_USER} -p 5432 -h localhost  -f ${f} || true ;;
>                 *.sql.gz) echo "$0: running $db $f"; gunzip < "$f" | psql ${db} -U ${POSTGRES_USER} -p 5432 -h localhost || true ;;
>                 *)        echo "$0: ignoring $db $f" ;;
>             esac
>             echo
>         done;
>         done;
>         # Put lock file to make sure entry point scripts were run
>         touch ${SETUP_LOCKFILE}
>     else
>         return 0
>     fi
> ```

Hi @schulzsebastian  the reason why there is that variable `SINGLE_DB` is that when you create multiple databases ie `data, gis, sample` and then you also choose to run a SQL script against the database it ensures that the SQL script will be executed against the first database listed there which would be `data`.

With your approach, it basically means any script will be executed against all database which to me does not make sense.

**Comment by schulzsebastian** [comment]
Ok, thank you for quick response, I understand. I used this for testing reason - same database for testing environment and the main one. Maybe it could be the extra feature.
Best regards!
