### ISSUE TITLE
Mounting volumes 

### ISSUE THREAD

**Issue by volkanunsal** [kartoza/docker-postgis#17]
While mounting a volume from my file system, I encountered this permission issue:

```bash
Initializing Postgres Database at /var/lib/postgresql/9.3/main
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
```

My fig file looks like this

```yml
volumes:
  - ~/postgres_data:/var/lib/postgresql
```

EDIT: I noticed this is addressed in the documentation, but I'm not sure what "sufficient permissions" means. Would be great to know.

**Comment by volkanunsal** [comment]
Figured it out. I had to change the location of the data directory and update the postgresql.conf file as well.

```ini
# postgresql.conf
data_directory=/data/postgresql
[program:postgres]
user=root
command=/start-postgis.sh
autorestart=true
stopsignal=INT

```

And

```bash
# start-postgis.sh
DATADIR="/data/postgresql"
```

**Comment by volkanunsal** [comment]
Sorry, I spoke too soon....

**Comment by volkanunsal** [comment]
Related to this issue:

https://github.com/boot2docker/boot2docker/issues/581

**Comment by timlinux** [comment]
For some history I since got an OSX laptop and I can replicate. As far as I know there is no easy fix since the boot2docker layer mounts your dirs via samba so permissions cant be propagated into linux nicely.
