### ISSUE TITLE
Conflicting port referenced in docker-compose.yml in README

### ISSUE THREAD

**Issue by tahnok** [kartoza/docker-postgis#174]
The README states:

> The docker compose recipe will expose PostgreSQL on port 25432 (to prevent potential conflicts with any local database instance you may have).

But the [docker-compose.yml](https://github.com/kartoza/docker-postgis/blob/develop/docker-compose.yml#L23) uses port 5432

**Comment by NyakudyaA** [comment]
@tahnok Can you fix this, please. we accept PR

**Comment by tahnok** [comment]
Sure thing, although I'm not sure which one "wins". Should the docker-compose.yml use 25432

**Comment by NyakudyaA** [comment]
@tahnok the docker-compose should use 25432
