### ISSUE TITLE
raster2pgsql missing

### ISSUE THREAD

**Issue by moldhouse** [kartoza/docker-postgis#175]
raster2pgsql seems to be missing in usr/lib/postgresql/12/bin when installing.

**Comment by NyakudyaA** [comment]
@moldhouse raster2pgsql is not installed by default in the image. We try to keep the image lightweight and not install a lot of things. If you really need it you need to install postgis into the container or image whichever is more preferable for you

**Comment by moldhouse** [comment]
Ok thanks, I understood that raster2pgsql would come with every distribution of postgis by default. 
But maybe I'm misunderstanding the way that Postgis is installed in this docker image?

**Comment by NyakudyaA** [comment]
> Ok thanks, I understood that raster2pgsql would come with every distribution of postgis by default.
> But maybe I'm misunderstanding the way that Postgis is installed in this docker image?

We install the following https://github.com/kartoza/docker-postgis/blob/develop/Dockerfile#L22

But raster2pgsql can only be installed by running `apt-get install -y postgis`

**Comment by moldhouse** [comment]
Ok thanks!
