### ISSUE TITLE
Extensions only installed to specified DB 

### ISSUE THREAD

**Issue by moldhouse** [kartoza/docker-postgis#179]
When using POSTGRES_MULTIPLE_EXTENSIONS in docker to add extensions, they are only installed in the db 'POSTGRES_DBNAME'. If for testing purposes, a database is created by a template, POSTGRES_MULTIPLE_EXTENSIONS are not available.

**Comment by NyakudyaA** [comment]
> When using POSTGRES_MULTIPLE_EXTENSIONS in docker to add extensions, they are only installed in the db 'POSTGRES_DBNAME'. If for testing purposes, a database is created by a template, POSTGRES_MULTIPLE_EXTENSIONS are not available.

@moldhouse the template method was an old way to install and create database. We now favour the createdb command. So if you need to test with a different database why do not just use  `POSTGRES_DBNAME` where you specify a lot of different databases.

If you still think this could be a useful feature we welcome a PR

**Comment by moldhouse** [comment]
Thanks for replying. I think the question is, wether it would make sense to install POSTGRES_MULTIPLE_EXTENSIONS to template1 by default as some frameworks generate test databases of it or if that kind of usage is not favoured.

**Comment by NyakudyaA** [comment]
> Thanks for replying. I think the question is, wether it would make sense to install POSTGRES_MULTIPLE_EXTENSIONS to template1 by default as some frameworks generate test databases of it or if that kind of usage is not favoured.

It all depends. If you have a framework that generates test database against template1 and you can make a PR saying etc Django requires this etc we can review it . We mainly use frameworks that allow us to specify a target DB for test
