### ISSUE TITLE
Please provide import example for docker-compose

### ISSUE THREAD

**Issue by xermus** [kartoza/docker-postgis#184]
I am using docker-postgis using docker-compose. The problem is that I could not figure out how to import one (or many) .sql files after the container(s) have been provisioned.

Can someone tell me how to accomplish this?

**Comment by NyakudyaA** [comment]
You just need to mount the sql file as a volume or the whole folder

Volume:
- ./setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql

**Comment by xermus** [comment]
Thanks, it works.
