### ISSUE TITLE
Inconsistency between docker-entrypoint.sh and Dockerfile (version 11.0.25)

### ISSUE THREAD

**Issue by pslh** [kartoza/docker-postgis#198]
In https://github.com/kartoza/docker-postgis/blob/11.0-2.5/docker-entrypoint.sh
we read the comment:
``# This script will run as the postgres user due to the Dockerfile USER directive``

However there is no ``USER`` directive in the ``Dockerfile``:
https://github.com/kartoza/docker-postgis/blob/11.0-2.5/Dockerfile

Our tests suggest that the entrypoint script is in fact executed as ``root``.

We have not tested with other versions, however there is no trace of a ``USER`` directive in the master branch ``Dockerfile``.

**Comment by NyakudyaA** [comment]
Hi @pslh Will check it out and rectify

**Comment by pmav99** [comment]
This is true also in 12.1 release. I assume in 12 too.

Nevertheless, `setup-conf.sh` modifies `sysctl` so it needs to be run as root:
https://github.com/kartoza/docker-postgis/blob/f535c58085de916ad2bf0faa2d865d4a415644ef/setup-conf.sh#L53-L56

Perhaps an option would be to install `gosu` in the image and use it drop root privileges later on.

**Comment by NyakudyaA** [comment]
Covered in #245
