### ISSUE TITLE
Default wal_level should probably not be hot_standby

### ISSUE THREAD

**Issue by Dylan-DutchAndBold** [kartoza/docker-postgis#199]
We ran into the issue today that our database was failing because the `pg_wal` directory was eating up all disk space voor a small ~20 mb database. It's a database that handles a lot of i/o but remains small. Researching into the issue I noticed `wal_level` was set to `hot_standby`. Which seems to be a old mode for recovery but is now mapped to `replica`. However I guess for some people it would be `minimal`. So it should probably be a bit more documented and configurable through an environment variable instead of setting it through `EXTRA_CONF`. In our case `minimal` is fine. We backup the tiny database hourly and loss of data is not a big issue for this database.

Source:
https://www.postgresql.org/docs/12/runtime-config-wal.html

Proposed solution:

* Change `hot_standby` to `replica`
* Allow configuration of wal/archiving values through ENV vars.
* Document these vars with references to PostgreSQL docs

**Comment by NyakudyaA** [comment]
> We ran into the issue today that our database was failing because the `pg_wal` directory was eating up all disk space voor a small ~20 mb database. It's a database that handles a lot of i/o but remains small. Researching into the issue I noticed `wal_level` was set to `hot_standby`. Which seems to be a old mode for recovery but is now mapped to `replica`. However I guess for some people it would be `minimal`. So it should probably be a bit more documented and configurable through an environment variable instead of setting it through `EXTRA_CONF`. In our case `minimal` is fine. We backup the tiny database hourly and loss of data is not a big issue for this database.
> 
> Source:
> https://www.postgresql.org/docs/12/runtime-config-wal.html
> 
> Proposed solution:
> 
>     * Change `hot_standby` to `replica`
> 
>     * Allow configuration of wal/archiving values through ENV vars.
> 
>     * Document these vars with references to PostgreSQL docs

Thanks for writing this. I will investigate when i have some free moment but you can also take a stab at it and will review your PR

**Comment by Dylan-DutchAndBold** [comment]
> > We ran into the issue today that our database was failing because the `pg_wal` directory was eating up all disk space voor a small ~20 mb database. It's a database that handles a lot of i/o but remains small. Researching into the issue I noticed `wal_level` was set to `hot_standby`. Which seems to be a old mode for recovery but is now mapped to `replica`. However I guess for some people it would be `minimal`. So it should probably be a bit more documented and configurable through an environment variable instead of setting it through `EXTRA_CONF`. In our case `minimal` is fine. We backup the tiny database hourly and loss of data is not a big issue for this database.
> > Source:
> > https://www.postgresql.org/docs/12/runtime-config-wal.html
> > Proposed solution:
> > ```
> > * Change `hot_standby` to `replica`
> > 
> > * Allow configuration of wal/archiving values through ENV vars.
> > 
> > * Document these vars with references to PostgreSQL docs
> > ```
> 
> Thanks for writing this. I will investigate when i have some free moment but you can also take a stab at it and will review your PR

Sure, will do, should not create any breaking changes anyway.
