### ISSUE TITLE
Collation always set to C.UTF-8

### ISSUE THREAD

**Issue by yamroz** [kartoza/docker-postgis#201]
Hello,

I have a problem - I need the database to run with en_US.UTF-8 collation and as far as I understood from documentation this should be the defaults setting. But for unknown reason this is not the case - database always reports as C.UTF-8.
I checked it with 9.6-2.4 image and 12.0

Is there any chance to check what is happening there?

Thank you!

**Comment by NyakudyaA** [comment]
Please test out with the tag latest to see if it’s working
