### ISSUE TITLE
EXTRA_CONF not working for 9.6-2.4

### ISSUE THREAD

**Issue by default-work** [kartoza/docker-postgis#207]
```bash

#!/bin/bash -e
[ "$(docker container ls | grep -c poleznygorodru_postgis_1)" == "1" ] && docker stop poleznygorodru_postgis_1
[ "$(docker container ls --all | grep -c poleznygorodru_postgis_1)" == "1" ] && docker container rm poleznygorodru_postgis_1
docker run -d --rm -p 5432:5432 -v /var/lib/docker/volumes/poleznygorodru_pgdata/_data:/var/lib/postgresql \
-e POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,pg_stat_statements,pg_shard \
-e EXTRA_CONF="shared_preload_libraries='pg_stat_statements,pg_shard'\npg_stat_statements.max = 10000\npg_stat_statements.track=all" \
--name poleznygorodru_postgis_1 --network web kartoza/postgis:9.6-2.4
```

```bash
 docker exec -it -u postgres poleznygorodru_postgis_1 psql -U postgres -c "SELECT * FROM pg_stat_statements;"

```

```
ERROR:  pg_stat_statements must be loaded via shared_preload_libraries
```

**Comment by NyakudyaA** [comment]
Hi, @funcelotwork That has not yet been ported to that branch.  Currently, it's in 11 and 12 image
Even the POSTGRES_MULTIPLE_EXTENSIONS doesn't exist in 9.6

**Comment by default-work** [comment]
@NyakudyaA i added EXTRA_CONF to 9.6-2.4 branch, check it out please

**Comment by NyakudyaA** [comment]
> @NyakudyaA i added EXTRA_CONF to 9.6-2.4 branch, check it out, please

@funcelotwork please fix the failing test.

**Comment by default-work** [comment]
> 
> 
> > @NyakudyaA i added EXTRA_CONF to 9.6-2.4 branch, check it out, please
> 
> @funcelotwork please fix the failing test.
@NyakudyaA I did not touch Docker compose, so it is not my fault, this is your image that is failing on CI/CD. I suppose you have to recheck logs or fix environments, cause i did not touch Docker compose at all. If you recheck you CI/CD env, then probably it will compile

**Comment by NyakudyaA** [comment]
> > > @NyakudyaA i added EXTRA_CONF to 9.6-2.4 branch, check it out, please
> > 
> > 
> > @funcelotwork please fix the failing test.
> > @NyakudyaA I did not touch Docker compose, so it is not my fault, this is your image that is failing on CI/CD. I suppose you have to recheck logs or fix environments, cause i did not touch Docker compose at all. If you recheck you CI/CD env, then probably it will compile

Hi @funcelotwork When you make a PR it should run until the test past so that I can merge them. The changes you added did not pass. If you are not in a hurry for this feature I will take a look during my free time

**Comment by default-work** [comment]
@NyakudyaA chechout PR, please https://github.com/kartoza/docker-postgis/pull/208

**Comment by NyakudyaA** [comment]
Will do first thing in the morning
