### ISSUE TITLE
Env variable PG_WAL_KEEP_SEGMENTS is ignored.

### ISSUE THREAD

**Issue by zingi** [kartoza/docker-postgis#222]
In the **setup-conf.sh** the variable **wal_keep_segments** is first set like this:
https://github.com/kartoza/docker-postgis/blob/a7244db7f3405d976b8f150043e2ff3805bfd5aa/setup-conf.sh#L26
but afterwards it is set to a hardcoded value:
https://github.com/kartoza/docker-postgis/blob/a7244db7f3405d976b8f150043e2ff3805bfd5aa/setup-conf.sh#L30

**Comment by zingi** [comment]
If somebody needs a temporary fix, you can add this line to your **Dockerfile**:
```Dockerfile
RUN sed -i '/wal_keep_segments= 64/d' /setup-conf.sh
``` 
it deletes the line with the hardcoded value.

**Comment by NyakudyaA** [comment]
> If somebody needs a temporary fix, you can add this line to your **Dockerfile**:
> 
> ```dockerfile
> RUN sed -i '/wal_keep_segments= 64/d' /setup-conf.sh
> ```
> 
> it deletes the line with the hardcoded value.

Rather make a PR and fix this quickly than a work around

**Comment by zingi** [comment]
PR: https://github.com/kartoza/docker-postgis/pull/223
