### ISSUE TITLE
Entrypoint script is hanging if we list existing table to stdout

### ISSUE THREAD

**Issue by lucernae** [kartoza/docker-postgis#227]
I encountered that the entrypoint stops (not just the log, but the executions is hanging), whenever there is a line like this:

```psql -l```

I propose that these lines be executed in a wrapper so the line returns the correct result.
Most of the time, these lines are used to check that the database exists or up, so the output was not necessary. We just want to know the exit code.

**Comment by NyakudyaA** [comment]
Fixed
