### ISSUE TITLE
Using pg_prewarm

### ISSUE THREAD

**Issue by TimMcCauley** [kartoza/docker-postgis#229]
I am trying to understand if I am able to use the `pg_prewarm` extension with this very helpful image. I can enable the extension it the database itself and I can also make sure it is a preloaded library: 

```sql
gis=# show shared_preload_libraries;
 shared_preload_libraries
--------------------------
 pg_prewarm
(1 row)
```

But when I run [this simple example](https://blog.dbi-services.com/pre-warming-the-buffer-cache-in-postgresql/) it has no effect. Every time I restart the container and run the query it will take the same time, the subsequent query will then be as expected much faster.

If I however use postgres installed on the host within ubuntu 18.04 itself it does `auto prewarm` as expected.

Do you see me doing anything wrong here or is this something docker/cache related that is non trivial to investigate/understand?

**Comment by NyakudyaA** [comment]
@TimMcCauley this should work as you have done. I will look into it and revert

**Comment by TimMcCauley** [comment]
Thank you @NyakudyaA !
