### ISSUE TITLE
Can't run docker build with ubuntu 14.04

### ISSUE THREAD

**Issue by Gustry** [kartoza/docker-postgis#23]
I'm trying to run docker build, but it failed each time : 
``The following packages have unmet dependencies:
 postgresql-9.3-postgis-2.1 : Depends: libgdal1h (>= 1.9.0) but it is not going to be installed``

I tried many hacks, but without success keeping ubuntu 14.04. It works using ubuntu:latest, can we switch ?

CC : @timlinux

**Comment by timlinux** [comment]
Yes please switch and make a PR. Thanks

**Comment by timlinux** [comment]
Ok I eventually fixed this by swtching to a debian stable base image. I also enabled hstore and topology extensions by default as I want to give a 'works out he box' experience.
