### ISSUE TITLE
pgrouting not in 12.0 branch anymore

### ISSUE THREAD

**Issue by nilsnolde** [kartoza/docker-postgis#236]
I [contributed](https://github.com/kartoza/docker-postgis/pull/167) pgRouting v3.x a few months back, but it seems it didn't survive a later re-arrangement in `Dockerfile`, it was probably forgotten in this commit:
https://github.com/kartoza/docker-postgis/commit/3cec047fcbb0efeacbaa0bc30d6de70de1ca94c3#diff-3254677a7917c6c01f55212f86c57fbf

Can we add it again?

**Comment by lucernae** [comment]
Yes, I think so too, CC @NyakudyaA , will it work if we just put pgrouting in POSTGRES_MULTIPLE_EXTENSION?

@nilsnolde , if you are okay with it, can you contribute a scenario that uses pgrouting/example of it.
We recently tries to make a standardized scenario tests like [this](https://github.com/kartoza/docker-postgis/tree/develop/scenario_tests):
Many people now uses our image differently, we want to make sure their use case is properly tested if we add more features.
If we have some scenario to tests, it can be used to make sure future changes does not break it.

**Comment by nilsnolde** [comment]
Sure, if you're ok with this for the test:
- have custom `docker-compose.yml` including pgrouting in `POSTGRES_MULTIPLE_EXTENSIONS`
- run a python script against it checking the `pg_available_extensions`

?

**Comment by NyakudyaA** [comment]
> Yes, I think so too, CC @NyakudyaA , will it work if we just put pgrouting in POSTGRES_MULTIPLE_EXTENSION?
> 
> @nilsnolde , if you are okay with it, can you contribute a scenario that uses pgrouting/example of it.
> We recently tries to make a standardized scenario tests like [this](https://github.com/kartoza/docker-postgis/tree/develop/scenario_tests):
> Many people now uses our image differently, we want to make sure their use case is properly tested if we add more features.
> If we have some scenario to tests, it can be used to make sure future changes does not break it.

pgrouting will not break anything. In order to to use that POSTGRES_MULTIPLE_EXTENSION you will need pgrouting to be installed. I think you should make it a default extension installed in https://github.com/kartoza/docker-postgis/blob/develop/scripts/env-data.sh#L173. we do not currently have test for extensions maybe it will be nice to add and test if the mandatory extensions are working fine

Can you just add it @nilsnolde

**Comment by NyakudyaA** [comment]
> Sure, if you're ok with this for the test:
> 
>     * have custom `docker-compose.yml` including pgrouting in `POSTGRES_MULTIPLE_EXTENSIONS`
> 
>     * run a python script against it checking the `pg_available_extensions`
> 
> 
> ?

You can just copy the example test in scenario test, modify it and add the env variable for extension in the docker compose

**Comment by nilsnolde** [comment]
Ok, will later add pgrouting to install section, default extensions, upate readme etc. PR to `12.0` or `develop`?

Cool, thanks @NyakudyaA  for the testing tip.

**Comment by NyakudyaA** [comment]
> Ok, will later add pgrouting to install section, default extensions, upate readme etc. PR to `12.0` or `develop`?
> 
> Cool, thanks @NyakudyaA for the testing tip.

PR to develop and then we can merge to 12
