### ISSUE TITLE
run container with environment variables - question

### ISSUE THREAD

**Issue by EricYang11** [kartoza/docker-postgis#244]
I'm trying to run a container with a username, password and extensions using the following command: 
docker --run postgis --restart=always -p 5432:5432 -d -t kartoza/postgis:12.0 -e POSTGRES_USER=admin -e POSTGRES_PASS=password -e POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting 

but I don't think I've done the environment settings properly because when I try to connect to it, it says that 

could not initiate GSSAPI security context: The operation or option is not available
could not initiate GSSAPI security context: Credential for asked mech-type mech not found in the credential handle
FATAL: password authentication failed for user "admin"
FATAL: password authentication failed for user "admin"

**Comment by NyakudyaA** [comment]
-e POTS_PASS where did that come from. Can you try to use the provided docker-compose for an example

**Comment by EricYang11** [comment]
Sorry, that was a typo

**Comment by NyakudyaA** [comment]
Are you not passing other variables that are not supposed to be there. Because GSSAPI seems like an error related to initidb

**Comment by EricYang11** [comment]
could you give me a sample of what a proper run container command should look like with the variables

**Comment by NyakudyaA** [comment]
I think the 12.0 image doesn’t have pgrouting if I am correct. Try to run it using kartoza/postgis which will use the latest image

**Comment by EricYang11** [comment]
So I just take off the :12.0 and pgrouting from the command and that's what it should look like?

**Comment by EricYang11** [comment]
Oh, I forgot to mention that the error prompt is from pgadmin when I'm trying to connect

**Comment by NyakudyaA** [comment]
What version of pgadmin, then maybe you need to search the error on stack exchange about pgadmin error
