### ISSUE TITLE
ogr2ogr fails with image 12.0 and above

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-postgis#248]
# Problem

Running ogr2ogr is failing for the PostgreSQL 12 images. Apparently this was fixed in https://github.com/OSGeo/gdal/commit/963618e77de4eee5e7321f5f5ca7abc2b7287fa2

So we should be running gdal > 3.02 to fix this. 

https://gis.stackexchange.com/questions/342246/ogr2ogr-from-file-to-postgresql-12-table-fails

# Solution
Investigate how to install gdal > 3 in Debian buster

**Comment by sabman** [comment]
Running into kinda of a circular dependency issue: 

1. install `pg12` `pgis3` (as a dependency `libgdal2` is installed)
2. If we try to install `gdal` `> 3.x` it complains `libgdal2` is install - if you force it then it uninstalls `pgis3`

Only way I got it working so far is by compiling gdal 3 from source - but not ideal, a bit stuck... not sure how to proceed.

**Comment by NyakudyaA** [comment]
@sabman You need to do a build based on Ubuntu.

Ubuntu 20.04 installs gdal 3 by default 

https://github.com/kartoza/docker-postgis#alternative-base-distributions-builds

For Debian builds I don’t know if there is a new version after buster that comes with gdal 3

**Comment by NyakudyaA** [comment]
This has been solved in the base image. https://github.com/kartoza/docker-postgis/blob/postgres-base/Dockerfile#L26
