### ISSUE TITLE
Set database timezone to other then `UTC`

### ISSUE THREAD

**Issue by Jean-Zombie** [kartoza/docker-postgis#251]
Hey there.

I am trying to set my timezone to a different value other then 'UTC'. I am using 'docker-compose' and docker 'volume' to make my data persistent. I read the section about "Environment variables" here in the docs but I am hitting a wall. 

I managed to set the timezone for the database image in my dockerfile:
```
ENV TZ='Europe/Berlin'
```
Logging into a running container and checking `date` gives me the correct time. But the database time still shows `UTC`. I also checked `postgresql.conf` in the container and I can see `timezone = 'Etc/UTC'` is not commented out. As far as I understand commenting `timezone` out should force the database to fall back to the system time.

Is there a way to set the timezone permanently, preferably with `docker-compose`? 

I already tried mounting the database to my host with `data-volume:/var/lib/postgresql` and changing the `postgresql.conf` there but then I end up with a total different cluster initialization 😃

**Comment by NyakudyaA** [comment]
> Hey there.
> 
> I am trying to set my timezone to a different value other then 'UTC'. I am using 'docker-compose' and docker 'volume' to make my data persistent. I read the section about "Environment variables" here in the docs but I am hitting a wall.
> 
> I managed to set the timezone for the database image in my dockerfile:
> 
> ```
> ENV TZ='Europe/Berlin'
> ```
> 
> Logging into a running container and checking `date` gives me the correct time. But the database time still shows `UTC`. I also checked `postgresql.conf` in the container and I can see `timezone = 'Etc/UTC'` is not commented out. As far as I understand commenting `timezone` out should force the database to fall back to the system time.
> 
> Is there a way to set the timezone permanently, preferably with `docker-compose`?
> 
> I already tried mounting the database to my host with `data-volume:/var/lib/postgresql` and changing the `postgresql.conf` there but then I end up with a totally different cluster initialization smiley

Currently, we do not have a variable to do this. You can create a PR that sets the env variable for the PostgreSQL conf to read. This should be easy to do. We will review your PR

**Comment by Jean-Zombie** [comment]
Thanks for the quick reply. I might give it a shot!

**Comment by NyakudyaA** [comment]
This can be set per session. Have also added an env variable to change this
