### ISSUE TITLE
REPLICATION_PASS security issue

### ISSUE THREAD

**Issue by hb9fxq** [kartoza/docker-postgis#252]
https://github.com/kartoza/docker-postgis/blob/729d6d94fa282e08677639e2e05899edc6a22e47/scripts/env-data.sh#L207-L209

...defaults to replicator if not set by environment -> in my eyes that is a security issue if deployed on a internet facing server with ALLOW_IP_RANGE=0.0.0.0/0

My suggestion: 
- Generate secure random password 
- Disable login for User replicator by default
- only add the default user to pg_hba.conf instead of all by default 

Is there any other mechanism that I may have missed?

**Comment by NyakudyaA** [comment]
> https://github.com/kartoza/docker-postgis/blob/729d6d94fa282e08677639e2e05899edc6a22e47/scripts/env-data.sh#L207-L209
> 
> ...defaults to replicator if not set by environment -> in my eyes that is a security issue if deployed on a internet facing server with ALLOW_IP_RANGE=0.0.0.0/0
> 
> My suggestion:
> 
>     * Generate secure random password

You can use docker secrets which will not expose the running container env variables
> 
>     * Disable login for User replicator by default
This user has RO access to the database.
> 
>     * only add the default user to pg_hba.conf instead of all by default
> 
> 
> Is there any other mechanism that I may have missed?

@krippendorf in a production environment why would you want to run the setup with defaults. The env variables are there so that you can pass strong credentials to the running container.

**Comment by hb9fxq** [comment]
I fully understand your points, but my guess would be, that users see the replaction vars as kind of optional. 

e.g. 
`

> csrn-mapper-db:
>     image: kartoza/postgis:12.0
>     volumes:
>       - postgis-data:/var/lib/postgresql
>     environment:
>       # If you need to create multiple database you can add coma separated databases eg gis,data
>       - POSTGRES_DB=csrn-mapper-db
>       - POSTGRES_USER=docker
>       - POSTGRES_PASS=mySuperSecurePassword..evenWithDockerSecretsEtc
>       - ALLOW_IP_RANGE=0.0.0.0/0
>       # Add extensions you need to be enabled by default in the DB. Default are the five specified below
>       - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
>     ports:
>       - 1442:5432
>     restart: on-failure

`

Would give no indication that the replication account is unsecured..... maybe on more option would be to set REPLICATION_PASS to default to POSTGRES_PASS if not provided!?

**Comment by NyakudyaA** [comment]
> I fully understand your points, but my guess would be, that users see the replaction vars as kind of optional.

What about just making the README more verbose ?
> 
> e.g.
> `
> 
> > csrn-mapper-db:
> > image: kartoza/postgis:12.0
> > volumes:
> > - postgis-data:/var/lib/postgresql
> > environment:
> > # If you need to create multiple database you can add coma separated databases eg gis,data
> > - POSTGRES_DB=csrn-mapper-db
> > - POSTGRES_USER=docker
> > - POSTGRES_PASS=mySuperSecurePassword..evenWithDockerSecretsEtc
> > - ALLOW_IP_RANGE=0.0.0.0/0
> > # Add extensions you need to be enabled by default in the DB. Default are the five specified below
> > - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
> > ports:
> > - 1442:5432
> > restart: on-failure
> 
> `
> 
> Would give no indication that the replication account is unsecured..... maybe on more option would be to set REPLICATION_PASS to default to POSTGRES_PASS if not provided!?

If you have defined `ALLOW_IP_RANGE` and `IP_LIST` access to your database will be restricted to a specific subnet and list of ip address. So even if you forget to set your credentials for REPLICATION USER and PASS the most they could do is query your DB provided they are able to guess your IP

**Comment by NyakudyaA** [comment]
Fixed this made the README more verbose
