### ISSUE TITLE
Could not map anonymous shared memory: Cannot allocate memory

### ISSUE THREAD

**Issue by L0rdCr1s** [kartoza/docker-postgis#254]
I tried it on my arch linux system it works well but when run this image on ubuntu i get this log

```
database_1  | performing post-bootstrap initialization ... ok                                                                                                       
database_1  | syncing data to disk ... ok                                                                                                                           
database_1  |                                                                                                                                                       
database_1  | WARNING: enabling "trust" authentication for local connections
database_1  | You can change this by editing pg_hba.conf or using the option -A, or
database_1  | --auth-local and --auth-host, the next time you run initdb.
database_1  |                                                                                                                                                       
database_1  | Success. You can now start the database server using:                                                                                                 
database_1  |                                                                                                                                                       
database_1  |     /usr/lib/postgresql/11/bin/pg_ctl -D /var/lib/postgresql/11/main -l logfile start                                                                 
database_1  |                                                                                                                                                       
database_1  | 2020-06-13 10:55:24.365 UTC [44] LOG:  listening on IPv4 address "127.0.0.1", port 5432                                                               
database_1  | 2020-06-13 10:55:24.378 UTC [44] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"                                                   
database_1  | 2020-06-13 10:55:24.387 UTC [44] FATAL:  could not map anonymous shared memory: Cannot allocate memory                                                
database_1  | 2020-06-13 10:55:24.387 UTC [44] HINT:  This error usually means that PostgreSQL's request for a shared memory segment exceeded available memory, swap space, or huge pages. To reduce the request size (currently 545660928 bytes), reduce PostgreSQL's shared memory usage, perhaps by reducing shared_buffers or max_connections.
database_1  | 2020-06-13 10:55:24.389 UTC [44] LOG:  database system is shut down                                                                                   
database_1  | psql: could not connect to server: No such file or directory                                                                                          
database_1  |   Is the server running locally and accepting
database_1  |   connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
here is my docker-compose setup

```
version: "3"

volumes:
  postgis-data:

.....

  database:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
    env_file:
      - .env.prod.database
    ports:
      - 5434:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

.....

```

my .env.prod.database

```
POSTGRES_USER=********
POSTGRES_PASSWORD=********
POSTGRES_DB=********
```
i tried a different version of postgis 11.0-2.5 and i still get the same error, is there something i'm doing wrong maybe

**Comment by NyakudyaA** [comment]
> I tried it on my arch linux system it works well but when run this image on ubuntu i get this log
> 
> ```
> database_1  | performing post-bootstrap initialization ... ok                                                                                                       
> database_1  | syncing data to disk ... ok                                                                                                                           
> database_1  |                                                                                                                                                       
> database_1  | WARNING: enabling "trust" authentication for local connections
> database_1  | You can change this by editing pg_hba.conf or using the option -A, or
> database_1  | --auth-local and --auth-host, the next time you run initdb.
> database_1  |                                                                                                                                                       
> database_1  | Success. You can now start the database server using:                                                                                                 
> database_1  |                                                                                                                                                       
> database_1  |     /usr/lib/postgresql/11/bin/pg_ctl -D /var/lib/postgresql/11/main -l logfile start                                                                 
> database_1  |                                                                                                                                                       
> database_1  | 2020-06-13 10:55:24.365 UTC [44] LOG:  listening on IPv4 address "127.0.0.1", port 5432                                                               
> database_1  | 2020-06-13 10:55:24.378 UTC [44] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"                                                   
> database_1  | 2020-06-13 10:55:24.387 UTC [44] FATAL:  could not map anonymous shared memory: Cannot allocate memory                                                
> database_1  | 2020-06-13 10:55:24.387 UTC [44] HINT:  This error usually means that PostgreSQL's request for a shared memory segment exceeded available memory, swap space, or huge pages. To reduce the request size (currently 545660928 bytes), reduce PostgreSQL's shared memory usage, perhaps by reducing shared_buffers or max_connections.
> database_1  | 2020-06-13 10:55:24.389 UTC [44] LOG:  database system is shut down                                                                                   
> database_1  | psql: could not connect to server: No such file or directory                                                                                          
> database_1  |   Is the server running locally and accepting
> database_1  |   connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
> ```
> 
> here is my docker-compose setup
> 
> ```
> version: "3"
> 
> volumes:
>   postgis-data:
> 
> .....
> 
>   database:
>     image: kartoza/postgis:12.0
>     volumes:
>       - postgis-data:/var/lib/postgresql
>     env_file:
>       - .env.prod.database
>     ports:
>       - 5434:5432
>     restart: on-failure
>     healthcheck:
>       test: "exit 0"
> 
> .....
> ```
> 
> my .env.prod.database
> 
> ```
> POSTGRES_USER=********
> POSTGRES_PASSWORD=********
> POSTGRES_DB=********
> ```
> 
> i tried a different version of postgis 11.0-2.5 and i still get the same error, is there something i'm doing wrong maybe

The error is caused by the fooliwng lines https://github.com/kartoza/docker-postgis/blob/develop/scripts/setup-conf.sh#L61

Maybe your memory settings on your machine are low. 

A quick solution would be for you to do a PR and change the 

```
kernel.shmmax=543252480
kernel.shmall=2097152
```

To use env variables which you can then control how much you need to allocate

**Comment by L0rdCr1s** [comment]
Yah you're right, i tried running the image alone without other services running and the error didn't show up, the problem is the server doesn't have enough memory, i guess a better solution will be to upgrade RAM because i will have to later on anyway, thank you.
