### ISSUE TITLE
Setup reasonable defaults for walsegsize

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-postgis#268]
There is maybe bug in env-data.sh
https://github.com/kartoza/docker-postgis/blob/12.0/env-data.sh#L148
WAL_SEGSIZE=1024

This creates on initdb
https://github.com/kartoza/docker-postgis/blob/12.0/setup-database.sh#L16
wal_segment_size as 1GB and wal_keep_segments are in your config 250 -
so your pg_wal-directory will expand to 250GB!

Default on postgres.conf in 16MB, should this be 10?

from Postgres 12 manual:
--wal-segsize=size
     Set the WAL segment size, in megabytes.

**Comment by NyakudyaA** [comment]
`WAL_SEGSIZE` and 
`wal_keep_segments`  are environment variables that can be configured on the startup of the container. You should lower them based on your need. I will, however, review the docker image and setup reasonable defaults

**Comment by B-RH** [comment]
>Default on postgres.conf in 16MB, should this be 10?

should be 16, power of 2
