### ISSUE TITLE
Mounting a volume - permission needed

### ISSUE THREAD

**Issue by romanzdk** [kartoza/docker-postgis#274]
When I want to mount a data volume it says 
    fixing permissions on existing directory /var/lib/postgresql/10/main ... initdb: could not change permissions of directory "/var/lib/postgresql/10/main": Operation not permitted

**Comment by vvavepacket** [comment]
I'm also getting this

![image](https://user-images.githubusercontent.com/8295642/92346999-9c88d900-f09c-11ea-8768-6501bc5f137b.png)

**Comment by vvavepacket** [comment]
I found a fix for this (specially if you are mounting a folder which has an existing data on it)

First, allow the container to install to an empty directory (create another folder)
Second, take note of the permissions to that new empty directory. Copy the chmod and chown attributes to your existing folder.
Last, reboot your container now pointing to the existing data.

It should fix the permission issue.

**Comment by NyakudyaA** [comment]
> I found a fix for this (specially if you are mounting a folder which has an existing data on it)
> 
> First, allow the container to install to an empty directory (create another folder)
> Second, take note of the permissions to that new empty directory. Copy the chmod and chown attributes to your existing folder.
> Last, reboot your container now pointing to the existing data.
> 
> It should fix the permission issue.

Thanks, Is this problem specific to the 10 image ?

**Comment by vvavepacket** [comment]
Yes, I have two versions running both 10 and 12 and permission issue is usually caused when you are mounting an existing directory and files that has a different permission that what the code is expecting.

**Comment by NyakudyaA** [comment]
> Yes, I have two versions running both 10 and 12 and permission issue is usually caused when you are mounting an existing directory and files that has a different permission that what the code is expecting.

I would suggest you can update the documentation and add that section for what file permissions are needed

**Comment by NyakudyaA** [comment]
Closing this as docker encourages people to use docker volumes and will update the documentation
