### ISSUE TITLE
Upgrade image to PostGIS 13

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-postgis#275]
# Problem

We need to upgrade the image to PostGIS 13

- [x] Change default authentification to scram-sha-256
- [x] Change other env variables as specified in release notes
- [x] Add any other goodies that are available in 13 release
- [x] Decide if we need to disable replication by default
- [x] Any other things we need to address

ping @lucernae Anything you can think of do a brain dump here. Will work on it on my free time

**Comment by frankhommers** [comment]
I think you mean Postgres 13. Not PostGIS ;-)

**Comment by NyakudyaA** [comment]
> I think you mean Postgres 13. Not PostGIS ;-)

Yeah, you right. I have already done the migration
