### ISSUE TITLE
/usr/lib/postgresql/*/bin not in PATH

### ISSUE THREAD

**Issue by frafra** [kartoza/docker-postgis#278]
Hi,
I was just trying to call `/usr/lib/postgresql/13/bin/ogr_fdw_info` but it looks that `/usr/lib/postgresql/13/bin` is not included in `$PATH`.

**Comment by NyakudyaA** [comment]
![ogrinfo](https://user-images.githubusercontent.com/2510900/101642019-28632600-3a3b-11eb-807c-d28413fe8f34.png)

I could not replicate

**Comment by frafra** [comment]
Hi,
you are using the full path. The directory is not included in the `PATH`, so if you type `ogr_fdw_info` you get a command not found error.

**Comment by NyakudyaA** [comment]
Will fix, just tested it
