### ISSUE TITLE
build 12.4 missing

### ISSUE THREAD

**Issue by mbernasocchi** [kartoza/docker-postgis#279]
@timlinux  @NyakudyaA Would it be possible to build 12.4?
Cheers Marco

**Comment by NyakudyaA** [comment]
Hi @mbernasocchi i will build it during the weekend

**Comment by mbernasocchi** [comment]
Great thanks, here we did automate builds on releases: https://github.com/gem/oq-qgis-server/blob/master/.github/workflows/build_docker_images.yml 
maybe it can help you?

**Comment by mbernasocchi** [comment]
@NyakudyaA I also noticed that the 12.1 container has Postgres 12.2 in it

**Comment by NyakudyaA** [comment]
> @NyakudyaA I also noticed that the 12.1 container has Postgres 12.2 in it

Hi, @mbernasocchi I think it was not tagged properly. I will build the image shortly and ping you. Thanks for the script. I will  incoperate it into our workflow for publishing new images

**Comment by NyakudyaA** [comment]
![image-com](https://user-images.githubusercontent.com/2510900/97269821-cbb6fd80-1836-11eb-9810-b525da487375.png)

@mbernasocchi I have created the image

**Comment by mbernasocchi** [comment]
will test it tomorrow. thaks a lot
