### ISSUE TITLE
Log message 'ERROR:  extension "pg_cron" does not exist' when upgrading from docker-postgis 12 to 13

### ISSUE THREAD

**Issue by s2074135** [kartoza/docker-postgis#283]
Hi

I ran into an error message when upgrading docker-postgis from version 12 to 13. When running pg_restore on my previously exported postgis database (with pg_dumpall), the following error popped up:

> ERROR:  extension "pg_cron" does not exist

Yet the restore completes and a quick test on the data showed no problems. It seems to me that pg_cron used to be installed in version 12 but is missing in version 13. 

Is the absence of pg_cron in version 13 by design? If yes, can that error just be ignored?

Thank you for any help and suggestions.

Regards Thomas

**Comment by NyakudyaA** [comment]
> Hi
> 
> I ran into an error message when upgrading docker-postgis from version 12 to 13. When running pg_restore on my previously exported postgis database (with pg_dumpall), the following error popped up:
> 
> > ERROR:  extension "pg_cron" does not exist
> 
> Yet the restore completes and a quick test on the data showed no problems. It seems to me that pg_cron used to be installed in version 12 but is missing in version 13.
> 
> Is the absence of pg_cron in version 13 by design? If yes, can that error just be ignored?
> 
> Thank you for any help and suggestions.
> 
> Regards Thomas

When I initially upgraded the image to version 13 the pg_cron extension had not yet been ported. But I see that it looks like it has been ported now. You can make a PR to add it back and I will merge it otherwise wait for me to update the image hopefully soon.

If you really need it you can add a bash script to add it as part of the image.

**Comment by s2074135** [comment]
@NyakudyaA, I am only vaguely familiar with Git procedures. As far as I understand it, you have added the feature back to the development branch. Is there anything for me left to do, to get it into version 13?

Thank you

Thomas

**Comment by NyakudyaA** [comment]
> @NyakudyaA, I am only vaguely familiar with Git procedures. As far as I understand it, you have added the feature back to the development branch. Is there anything for me left to do, to get it into version 13?
> 
> Thank you
> 
> Thomas

I will make a PR later today to merge the develop branch into the 13.0 branch and this will update the image

**Comment by s2074135** [comment]
@NyakudyaA, thank you for your help and of course thank you for providing us with a docker image of postgis.

**Comment by NyakudyaA** [comment]
This been fixed in develop. Will port to 13 and release a new version
