### ISSUE TITLE
Stuck on Setup master database

### ISSUE THREAD

**Issue by vvavepacket** [kartoza/docker-postgis#286]
I'm using the `kartoza/postgis:12.1` tag of this image and now it seems the container is getting stuck at this state

```
Add rule to pg_hba: 0.0.0.0/0
Add rule to pg_hba: replication replicator
Setup master database
```

Is there anyway to get the last working version of that tag? It seems a breaking change was applied since a new pushed to docker hub happen recently.

Thanks

**Comment by NyakudyaA** [comment]
Closing as we have new images working. If you still have this issue please reopen
