### ISSUE TITLE
user-defined db doesn't get the proper extensions

### ISSUE THREAD

**Issue by greghor** [kartoza/docker-postgis#287]
First of all, thank you very much for sharing the image. Really helpful. 

I try to run a container with a specific db name and some extensions. 

`docker run -d -v $PWD/mydatadir:/var/lib/postgresql -p 5432:5432 -e POSTGRES_USER=<myusr> -e POSTGRES_PASS=<mypwd> -e POSTGRES_DBNAME=<mydbname> -e POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting kartoza/postgis`

the command doesn't return any errors, I can see the db in the running container with the proper name. However, the db is not associated with the desired extensions. Am I doing smth wrong?

**Comment by NyakudyaA** [comment]
Hi @greghor the extensions you have supplied are also the default. You can skip them and they will be automatically installed. When you login to the dB and run \l what tables do you see.

I suggest you start the container in interactive mode or tail the logs when it's starting and share them.
 
If the problems persists try using a docker volume or run a tagged image I.e 13.0

**Comment by greghor** [comment]
Hi @NyakudyaA  and thank you for your answer.

after investigating a bit, I think the problem was on my side. I used `postgres` as a db name, and this likely causes some conflicts since this is the default name for the maintenance db is also `postgres` (forgive me if my interpretation is wrong here, I am not (yet) a db expert :) ). Anyway, if I choose an other db name like `foo`,  things are working as expected. I am closing the issue then.
