### ISSUE TITLE
persist backups data

### ISSUE THREAD

**Issue by npltr62** [kartoza/docker-postgis#297]
Hi,
I need to persist backups data, is it possible?
in my compose file

>    volumes:
>       - ./pgdata:/var/lib/postgresql
>       - ./backups:/backups

**Comment by NyakudyaA** [comment]
It should work, just make sure that if you create the folder for the pg data directory it has the correct permissions or let docker create it for you

**Comment by npltr62** [comment]
ok thanks, i created pgdata folder and it's working , unfortunatly backups directory it's not the case. 

![Capture d’écran 2021-03-04 200453](https://user-images.githubusercontent.com/40625762/110021052-906b9480-7d2a-11eb-80cf-c75a3bc757cb.png)

**Comment by NyakudyaA** [comment]
> ok thanks, i created pgdata folder and it's working , unfortunatly backups directory it's not the case.
> 
> ![Capture d’écran 2021-03-04 200453](https://user-images.githubusercontent.com/40625762/110016095-eb01f200-7d24-11eb-94e9-97a3d9327d77.png)

Backups directory is created at midnight according to the cron schedule

**Comment by npltr62** [comment]
you're meaning each midnight a backup directory will created. how can i check that? in the container journal?
