### ISSUE TITLE
Restore a backup on Startup

### ISSUE THREAD

**Issue by ghost** [kartoza/docker-postgis#298]
Hi - Just looking for a little guidance - don't have a lot of postgis / gres knowledge, but had lots of other.
Is it possible for me to restore a backup taken with pg_dump on startup of the container?

**Comment by NyakudyaA** [comment]
Yes, can you look at the section
 Running SQL scripts on container startup from the readme.

**Comment by ghost** [comment]
Sorry - I completely overlooked that section! My Bad
It states can only use .sql , .sql.gz and .sh, but because pg_dump outputs sql commands when it dumps the db, am I ok to just use this (rather large) dump file as if it was a sql script?

** Edit **

Yeah it works - cheers :)

**Comment by NyakudyaA** [comment]
@DavidSekula you can create a bash script that will run pg_restore no matter what format your pg_dump output format
