### ISSUE TITLE
Mounted initialization scripts trigger readonly filesystem on creation of lockfile.

### ISSUE THREAD

**Issue by bpasson** [kartoza/docker-postgis#300]
When deploying on Kubernetes with a Secret containing initialization sql scripts mounted to `/docker-entrypoint-initdb.d/` you get a readonly file system error, as the directory is mounted readonly by Kubernetes. The `/docker-entrypoint-initdb.d/.entry_point.lock` file should not be created inside that directory. Using secrets and configmaps as mounted files is an commonly used way to add scripts to images in stead of extending and making new images.

To add to this, the lockfile should be stored in persisted storage. This would keep the scripts get run again when starting the database which is already initialized potentially damaging the content.

**Comment by NyakudyaA** [comment]
@bpasson What suggestion do you have to combat this problem?

**Comment by lucernae** [comment]
@bpasson If you are looking for a work around, can you specify the mount to the file instead of the directory?
I also do it this way when mounting scripts from a configmap. But I never mount scripts from secrets, though.
The `/docker-entrypoint-initdb.d/` can still be mounted using a PV this way (and get overlaid with the individual files from the configmap mount).

Otherwise, we would be very happy to hear your suggestions.

**Comment by bpasson** [comment]
@lucernae It's true I can mount specific files. It's not ideal if you have more than one, as each one needs specific mapping. Concerning the lockfile (/docker-entrypoint-initdb.d/.entry_point.lock) used to see if the scripts should be run should be stored in persisted storage in stead of ephemeral storage. In the case of a pod relocation or restart the scripts are executed again, possibly breaking the database. Most people will mount /var/lib/postgresql as a volume, so somewhere inside there should be fine. This eliminates both issues. You can then mount init-scripts from Secrets and ConfigMaps as a directory and the lockfile is persistent though relocations and restarts ensuring the scripts are only run once or when IGNORE_INIT_HOOK_LOCKFILE is specified.

**Comment by NyakudyaA** [comment]
Fixed by new image
