### ISSUE TITLE
ARM64 / Apple Silicon builds in Docker Hub

### ISSUE THREAD

**Issue by agusterodin** [kartoza/docker-postgis#301]
The only version in Docker Hub is only x86-64. The image does not work on Apple Silicon (M1) even with Docker qemu emulation. Do you have any suggestions on how to get it to work?

**Comment by NyakudyaA** [comment]
Hi @agusterodin unfortunately we are not yet privileged enough to own the new shinny M1. Is there any docker image that is working on the new M1. If so can , which one is it. The idea is that we need to compare what base image the working image is using.

**Comment by agusterodin** [comment]
I have built an arm64 version on my machine. It appears to work perfectly. It is on the docker hub under jeffrosen1092/postgis:latest. Is there anything else I can do to help?

**Comment by NyakudyaA** [comment]
Thanks, @agusterodin, You could do a PR so that we can incorporate it with this image. 
We are also looking at various ways to tag our images so that they can be used for different situation ie redhat etc

**Comment by NyakudyaA** [comment]
And also can you add a link to your dockerhub

**Comment by agusterodin** [comment]
https://hub.docker.com/repository/docker/jeffrosen1092/postgis

**Comment by agusterodin** [comment]
What exactly should the PR contain? I performed the build on my machine with this command `docker build -t kartoza/postgis git://github.com/kartoza/docker-postgis`.

Doesn't this boil down to updating the pipeline (and maybe dockerfile)? I've heard that people that build with Github Actions are blocked by the fact that you can't build ARM64 on their pipelines (similar to what is mentioned here https://github.com/postgis/docker-postgis/issues/216)

**Comment by NyakudyaA** [comment]
Thanks @agusterodin i think the link describes the issue clearly, I think the solution for now should be
* build the image locally 
* Investigate how GitHub actions can be improved to build images compatible for silicon - this should be the long term solutions but since we maintain this image pro-bono we will wait for solutions from the community or someone to sponsor us to develop a solution (GitHub action)
*

**Comment by janfilips** [comment]
> I have built an arm64 version on my machine. It appears to work perfectly. It is on the docker hub under jeffrosen1092/postgis:latest.

Well it's not anymore (and it did work for me perfectly)..  :-/

**Comment by agusterodin** [comment]
> > I have built an arm64 version on my machine. It appears to work perfectly. It is on the docker hub under jeffrosen1092/postgis:latest.
> 
> Well it's not anymore (and it did work for me perfectly).. :-/

My bad, see the above PR. There are official ARM64 builds on Docker Hub now! No need to use my stopgap image anymore.

**Comment by agusterodin** [comment]
Use this one instead, for example: kartoza/postgis:14-3.1

**Comment by janfilips** [comment]
Thank you very much big sir! :) :) :) 🥇
