### ISSUE TITLE
Make SSL Default in container

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-postgis#305]
https://pavelevstigneev.medium.com/postgresql-ssl-with-letsencrypt-b53051eacc22

**Comment by timlinux** [comment]
@NyakudyaA 

Currently the ssl forcing client to ssl is broken. Can you replace cert with md5 so the HBA config is something like this:

![image](https://user-images.githubusercontent.com/178003/117893545-85952900-b2b2-11eb-970b-fb6326fa752e.png)
