### ISSUE TITLE
directory sharing

### ISSUE THREAD

**Issue by startakovsky** [kartoza/docker-postgis#31]
Hello, Thank you for maintaining this postgres-docker repository. 

I am sharing directories as recommended by your Readme...  but when I start the container I get these errors below. I used to get other errors, but then I put this in: `sudo chmod -R 0777 .`

I am using a mac. How do you recommend I go about setting appropriate pemissions.

Thank you...

```
2015-12-03 14:52:25 UTC [21-1] FATAL:  could not create lock file "postmaster.pid": Permission denied
some-postgis_1 | 2015-12-03 14:52:25 UTC [26-1] FATAL:  data directory "/var/lib/postgresql/9.4/main" has wrong ownership
some-postgis_1 | 2015-12-03 14:52:25 UTC [26-2] HINT:  The server must be started by the user that owns the data directory.

```

**Comment by timlinux** [comment]
For OSX I recommend not using a volume for your database cluster because the volume shares are done using CIFS/SAMBA and the unix file permissions do not map to it. See also https://github.com/kartoza/docker-postgis/issues/17

**Comment by startakovsky** [comment]
Anytips on persisting my database storage? Perhaps some way to leverage another docker container?

**Comment by timlinux** [comment]
You can use a docker storage container (still vulnerable to overzealous stopped container removal though) or what I do is simply dump and restore. I use a little makefile to do:

```
make dbdump
```

and 

```
make dbrestore
```

Which for working on my OSX machine as a dev environment is fine. For production we use our rotating backups tools available here: https://github.com/kartoza/docker-sftp-backup - you could tweak that according to your needs (e.g. just saving local backups on a regular interval).
