### ISSUE TITLE
required WAL directory "pg_wal" does not exist

### ISSUE THREAD

**Issue by anneb** [kartoza/docker-postgis#317]
Postgres fails to start in a fresh container when previously created data exists in datadir
version/tag: kartoza/postgis:13-3.1

Steps to reproduce:
Initialize a database on host in /home/username/data:
```
rm -rf /home/username/data
mkdir /home/username/data
#succesful database creation and postgis listening on port 5432:
docker run --name postgis -ti --rm -e POSTGRES_PASS=docker -v /home/username/data:/var/lib/postgresql -p 5432:5432 kartoza/postgis:13-3.1
```

Try to use initialized database on the same host from a fresh container:
```
docker stop postgis
#postgres failed to start:
docker run --name postgis -ti --rm -e POSTGRES_PASS=docker -v /home/username/data:/var/lib/postgresql -p 5432:5432 kartoza/postgis:13-3.1
FATAL:  required WAL directory "pg_wal" does not exist
```

The documentation describes how to persist data on the host file system (-v hostdirectory:/var/lib/postgresql), but does not describe how or where to define WAL or the pg_wal directory for this case?

**Comment by NyakudyaA** [comment]
@anneb i have fixed this but you should be able to pass the env variable -e POSTGRES_INITDB_WALDIR=/var/lib/postgresql/pg_wal and then mount the volume but it should work by default now
