### ISSUE TITLE
Password is appended on each container start

### ISSUE THREAD

**Issue by bleleve** [kartoza/docker-postgis#319]
Hi there,

It seems that the password defined by the env var POSTGRES_PASS is appended on every restart of the container :

**1st start logs :**
postgresql_1  | [Entrypoint] GENERATED Postgres  PASSWORD:  xxxxxxxxxxxxxxxxxxxx
postgresql_1  |  PGPASSWORD Generated above:

**2nd start logs :**
postgresql_1  | [Entrypoint] GENERATED Postgres  PASSWORD:  xxxxxxxxxxxxxxxxxxxx
postgresql_1  | xxxxxxxxxxxxxxxxxxxx
postgresql_1  |  PGPASSWORD Generated above:

**3rd start logs :**
postgresql_1  | [Entrypoint] GENERATED Postgres  PASSWORD:  xxxxxxxxxxxxxxxxxxxx
postgresql_1  | xxxxxxxxxxxxxxxxxxxx
postgresql_1  | xxxxxxxxxxxxxxxxxxxx
postgresql_1  |  PGPASSWORD Generated above:

Content of the file /tmp/PGPASSWORD.txt (created by env-data.sh) after the 3rd restart :
root@c9541e65ee1e:/scripts# cat /tmp/PGPASSWORD.txt
xxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxx
root@c9541e65ee1e:/scripts#

I am using the image 13-3.

Anyone else having this issue ? I think the function pg_password() should use > instead of >>.

Thank you for your hard work 👍

**Comment by timlinux** [comment]
Thanks for this - probably a side effect of the new default random password we did to prevent security issues arising from using known default passwords. @NyakudyaA will you make a fix?

**Comment by bleleve** [comment]
You guys rocks!
