### ISSUE TITLE
Question: How could I use pg cron inside the container?

### ISSUE THREAD

**Issue by rmmariano** [kartoza/docker-postgis#322]
I'm not able to use pg cron inside the container and I do not know the reason.

I have a procedure that I would like to call inside `register` database.

Inside `gis` database I added the following cron job:

```
1 "*/1 * * * *" "CALL update_table()" "localhost" 5432 "register" "postgres" true
```

But a connection failed message appears on the console:

```
pg_cron scheduler started
cron job 1 starting: CALL update_table()
cron job 1 connection failed
```

I've already added a `.pgpass` file that allows me to use `psql` command without passing a password, but pg cron is not able to connect.

Would anyone know how I could fix it?

Thank you in advance.

**Comment by NyakudyaA** [comment]
> I'm not able to use pg cron inside the container and I do not know the reason.
> 
> I have a procedure that I would like to call inside `register` database.
> 
> Inside `gis` database I added the following cron job:
> 
> ```
> 1 "*/1 * * * *" "CALL update_table()" "localhost" 5432 "register" "postgres" true
> ```
> 
> But a connection failed message appears on the console:
> 
> ```
> pg_cron scheduler started
> cron job 1 starting: CALL update_table()
> cron job 1 connection failed
> ```
> 
> I've already added a `.pgpass` file that allows me to use `psql` command without passing a password, but pg cron is not able to connect.
> 
> Would anyone know how I could fix it?
> 
> Thank you in advance.

Please check https://github.com/citusdata/pg_cron/
