### ISSUE TITLE
POSTGRES_DB vs POSTGRES_DBNAME

### ISSUE THREAD

**Issue by eriktelepovsky** [kartoza/docker-postgis#323]
Hello. I'd like to ask, what's the difference between environment variables POSTGRES_DB and POSTGRES_DBNAME? Which one should I use? Or both?

Docs on Docker hub repository mentions both variables but I am confused which one to use and when:
https://hub.docker.com/r/kartoza/postgis/

**Comment by NyakudyaA** [comment]
> Hello. I'd like to ask, what's the difference between environment variables POSTGRES_DB and POSTGRES_DBNAME? Which one should I use? Or both?
> 
> Docs on Docker hub repository mentions both variables but I am confused which one to use and when: https://hub.docker.com/r/kartoza/postgis/

They are both used. The POSTGRES_DB is used with the official Postgres image so it can be used here.  See https://github.com/kartoza/docker-postgis/blob/develop/scripts/env-data.sh#L279
