### ISSUE TITLE
FATAL:  database "mydb" does not exist, but DATADIR is set

### ISSUE THREAD

**Issue by shortwavedave** [kartoza/docker-postgis#327]
I'm not sure what I'm missing here. I've set the DATADIR environment variable to /data, which is a mounted drive. It looks like postgres is writing to this drive:

```
root@container-0:/data# ls
base          pg_dynshmem    pg_logical    pg_replslot   pg_stat      pg_tblspc    pg_wal                postgresql.conf
global        pg_hba.conf    pg_multixact  pg_serial     pg_stat_tmp  pg_twophase  pg_xact               postmaster.opts
pg_commit_ts  pg_ident.conf  pg_notify     pg_snapshots  pg_subtrans  PG_VERSION   postgresql.auto.conf  postmaster.pid
```

Here are the startup logs

```
Add rule to pg_hba: 0.0.0.0/0
Add rule to pg_hba: replication replicator
Setup master database
2021-08-29 04:21:04.030 UTC [56] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-08-29 04:21:04.031 UTC [56] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-08-29 04:21:04.037 UTC [56] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-08-29 04:21:04.068 UTC [60] LOG:  database system was shut down at 2020-10-27 07:19:33 UTC
2021-08-29 04:21:04.069 UTC [61] postgres@postgres FATAL:  the database system is starting up
/var/run/postgresql:5432 - rejecting connections
2021-08-29 04:21:04.076 UTC [56] LOG:  database system is ready to accept connections
2021-08-29 04:21:04.077 UTC [68] FATAL:  database "mydb" does not exist
2021-08-29 04:21:04.080 UTC [56] LOG:  background worker "pg_cron launcher" (PID 68) exited with exit code 1
2021-08-29 04:21:05.082 UTC [73] FATAL:  database "mydb" does not exist
2021-08-29 04:21:05.084 UTC [56] LOG:  background worker "pg_cron launcher" (PID 73) exited with exit code 1
/var/run/postgresql:5432 - accepting connections
```

Here are my container settings:

```
        - name: postgis
          image: kartoza/postgis:12.4
          env:
            - name: POSTGRES_PASS
              value: '...'
            - name: POSTGRES_USER
              value: '...'
            - name: DATADIR
              value: '/data'
            - name: POSTGRES_INITDB_WALDIR
              value: '/data/pg_wal'
            - name: POSTGRES_DBNAME
              value: 'mydb'
            - name: POSTGRES_MULTIPLE_EXTENSIONS
              value: 'postgis,postgis_topology,postgis_raster,pgrouting'
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgis-data
              mountPath: /data
```

Any ideas what may be happening here?

**Comment by NyakudyaA** [comment]
> I'm not sure what I'm missing here. I've set the DATADIR environment variable to /data, which is a mounted drive. It looks like postgres is writing to this drive:
> 
> 
> 
> ```
> 
> root@container-0:/data# ls
> 
> base          pg_dynshmem    pg_logical    pg_replslot   pg_stat      pg_tblspc    pg_wal                postgresql.conf
> 
> global        pg_hba.conf    pg_multixact  pg_serial     pg_stat_tmp  pg_twophase  pg_xact               postmaster.opts
> 
> pg_commit_ts  pg_ident.conf  pg_notify     pg_snapshots  pg_subtrans  PG_VERSION   postgresql.auto.conf  postmaster.pid
> 
> ```
> 
> 
> 
> Here are the startup logs
> 
> 
> 
> ```
> 
> Add rule to pg_hba: 0.0.0.0/0
> 
> Add rule to pg_hba: replication replicator
> 
> Setup master database
> 
> 2021-08-29 04:21:04.030 UTC [56] LOG:  starting PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
> 
> 2021-08-29 04:21:04.031 UTC [56] LOG:  listening on IPv4 address "127.0.0.1", port 5432
> 
> 2021-08-29 04:21:04.037 UTC [56] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> 
> 2021-08-29 04:21:04.068 UTC [60] LOG:  database system was shut down at 2020-10-27 07:19:33 UTC
> 
> 2021-08-29 04:21:04.069 UTC [61] postgres@postgres FATAL:  the database system is starting up
> 
> /var/run/postgresql:5432 - rejecting connections
> 
> 2021-08-29 04:21:04.076 UTC [56] LOG:  database system is ready to accept connections
> 
> 2021-08-29 04:21:04.077 UTC [68] FATAL:  database "mydb" does not exist
> 
> 2021-08-29 04:21:04.080 UTC [56] LOG:  background worker "pg_cron launcher" (PID 68) exited with exit code 1
> 
> 2021-08-29 04:21:05.082 UTC [73] FATAL:  database "mydb" does not exist
> 
> 2021-08-29 04:21:05.084 UTC [56] LOG:  background worker "pg_cron launcher" (PID 73) exited with exit code 1
> 
> /var/run/postgresql:5432 - accepting connections
> 
> ```
> 
> 
> 
> Here are my container settings:
> 
> 
> 
> ```
> 
>         - name: postgis
> 
>           image: kartoza/postgis:12.4
> 
>           env:
> 
>             - name: POSTGRES_PASS
> 
>               value: '...'
> 
>             - name: POSTGRES_USER
> 
>               value: '...'
> 
>             - name: DATADIR
> 
>               value: '/data'
> 
>             - name: POSTGRES_INITDB_WALDIR
> 
>               value: '/data/pg_wal'
> 
>             - name: POSTGRES_DBNAME
> 
>               value: 'mydb'
> 
>             - name: POSTGRES_MULTIPLE_EXTENSIONS
> 
>               value: 'postgis,postgis_topology,postgis_raster,pgrouting'
> 
>           ports:
> 
>             - containerPort: 5432
> 
>               name: postgres
> 
>           volumeMounts:
> 
>             - name: postgis-data
> 
>               mountPath: /data
> 
> ```
> 
> 
> 
> Any ideas what may be happening here?

POSTGRES_INITDB_WALDIR can only be set for images >13.3-1

What permission does your mount point have ?

**Comment by shortwavedave** [comment]
@NyakudyaA Thanks for the response. The data directory has the following permissions:

```
drwxr-x---  18 postgres postgres 4096 Aug 12 05:31 data
```

I did initially have an issue with permissions when I first deployed the container (on kubernetes). I thought that I fixed it when I setup an init container that updated the permissions of the mounted drive - after that it seems like postgres is writing to it. perhaps there is a startup error that isn't shown? Before when I had the permissions problem, the error was clear in the terminal.

**Comment by shortwavedave** [comment]
Seems that there is a bug in the datadir logic (at least for the 12.0 branch). 

The env-data.sh script is sourced, and the DATADIR variable is set at the top of the file, so this logic doesn't do anything:
```
# If datadir is defined use this
if [ -n "${DATADIR}" ]; then
  DATADIR=${DATADIR}
fi
```

In local tests I removed the initialization at the top of the script, and changed that logic to
```
# If datadir is defined use this
if [ -n "${DATADIR}" ]; then
  DATADIR=${DATADIR}
else
  DATADIR="/var/lib/postgresql/${POSTGRES_MAJOR_VERSION}/main"
fi
```

This time it found the folder, but then I get this error (with an empty datadir):

```
2021-09-06 19:04:03.787 UTC [57] FATAL: "/data" is not a valid data directory
2021-09-06 19:04:03.787 UTC [57] DETAIL: File "/data/PG_VERSION" is missing.
```

I was wondering why the docker-compose works, but it just maps the entire postgres lib folder to a volume.

**Comment by NyakudyaA** [comment]
@shortwavedave the best solution would be to cherry pick some of the logic in the develop branch to the 12 branch. We would then release a new tag for that specific version

**Comment by NyakudyaA** [comment]
@shortwavedave it should be declared like this


DEFAULT_DATADIR="/var/lib/postgresql/${POSTGRES_MAJOR_VERSION}/main"

# If datadir is not defined, then use this
if [ -z "${DATADIR}" ]; then
  DATADIR=${DEFAULT_DATADIR}
fi
