### ISSUE TITLE
Support for plv8 extension

### ISSUE THREAD

**Issue by abhijitgujar86** [kartoza/docker-postgis#332]
It will be great if we can add support for plv8 extension as its more secure runs in sandbox.

**Comment by NyakudyaA** [comment]
@abhijitgujar86 we have no objection to this at all. Can you please try to make a PR and we will review it. Since this repo is mostly pro-bono work there is no guarantee that we will address this issue so soon unless you take initiative. We can give you pointers if you lost on where to make changes

**Comment by abhijitgujar86** [comment]
sure will give it try.

**Comment by NyakudyaA** [comment]
For now installation of plv8 does not support latest postgres version. I suggest we use the entry point bash script to setup and run this
