### ISSUE TITLE
PostgreSQL 9.5?

### ISSUE THREAD

**Issue by bhtek** [kartoza/docker-postgis#34]
Any plans to upgrade to PostgreSQL 9.5?

**Comment by timlinux** [comment]
Hi

Yes I will add PG 9.5 support soon.

Regards

Tim

**Comment by elcodedocle** [comment]
While it is not available here I added support for 9.5/postgis-2.2 on my fork ( elcodedocle/docker-postgis). Also available on dockerhub @ gael4imatia/docker-postgis . But be aware I will not be maintaining this fork, I'll be back to use this project as soon as it's updated (hopefully with a license file too, please! ;-) ).

**Comment by timlinux** [comment]
@elcodedocle could you just make a pull request from your repo. I will merge it and set up a new build target on docker hub.

Thanks!

Tim

**Comment by elcodedocle** [comment]
I send it on #39 Please consider adding a license file to the project. Thank you

**Comment by elcodedocle** [comment]
@timlinux So what about the upgrade? Is is not ok?

**Comment by NyakudyaA** [comment]
This has been fixed and we now have PostgreSQL 11 and the licence file added
