### ISSUE TITLE
Docker container not start

### ISSUE THREAD

**Issue by wlorenzetti** [kartoza/docker-postgis#340]
Hi I've a problem on a CentOS Linux release 7.9.2009 (Core)
I'm using the docker tag image 11.0-2.5, I know is very old, but at the moment we use it inside our G3W-SUITE docker...

On Debian or Ubutnu host I haven't any problems but with this Centos my contaner doesn't start and very quickly go donw with the follow error:

postgis_1  | rm: cannot remove '/etc/ssl/certs': Directory not empty
postgis_1  | rm: cannot remove '/etc/ssl/private': Directory not empty

Any idea about it?

Thanks in advance
Walter

**Comment by NyakudyaA** [comment]
> Hi I've a problem on a CentOS Linux release 7.9.2009 (Core) I'm using the docker tag image 11.0-2.5, I know is very old, but at the moment we use it inside our G3W-SUITE docker...
> 
> On Debian or Ubutnu host I haven't any problems but with this Centos my contaner doesn't start and very quickly go donw with the follow error:
> 
> postgis_1 | rm: cannot remove '/etc/ssl/certs': Directory not empty postgis_1 | rm: cannot remove '/etc/ssl/private': Directory not empty
> 
> Any idea about it?
> 
> Thanks in advance Walter

@wlorenzetti I believe these are related to some permission issues. Could you try to run the container with `--privileged` flag just to try it out. This is not recommended though.

Alternatively, check the following https://docs.datadoghq.com/security_monitoring/default_rules/cis-docker-1.2.0-5.12/

**Comment by wlorenzetti** [comment]
Thanks @NyakudyaA for reply :). I try with `--privileged` but it not work again.. It seems that try to mount `/etc/ssl` host directory.. but I don't set any volume options..
