### ISSUE TITLE
how to add EXTENSIONS timescaledb

### ISSUE THREAD

**Issue by xqhmz** [kartoza/docker-postgis#346]
POSTGRES_MULTIPLE_EXTENSIONS=timescaledb
SHARED_PRELOAD_LIBRARIES=timescaledb

what should   I add

**Comment by NyakudyaA** [comment]
> POSTGRES_MULTIPLE_EXTENSIONS=timescaledb
> SHARED_PRELOAD_LIBRARIES=timescaledb
> 
> what should   I add 

You are right there but I also assume you would need other extensions i.e
 
 ​      - ​POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,timescaledb

You can even exclude SHARED_PRELOAD_LIBRARIES=timescaledb because by default it is set to load timescaledb and pgcron

**Comment by xqhmz** [comment]
I use ​POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,timescaledb only
but error 
![image](https://user-images.githubusercontent.com/49462898/142806906-209cc543-95b8-49b2-b752-133feadd4a5a.png)

images: kartoza/postgis:11.5-2.8
version is too old ?

**Comment by NyakudyaA** [comment]
> I use ​POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,timescaledb only but error ![image](https://user-images.githubusercontent.com/49462898/142806906-209cc543-95b8-49b2-b752-133feadd4a5a.png)
> 
> images: kartoza/postgis:11.5-2.8 version is too old ?

@xqhmz Those changes have been applied to the 14 images. If you need them in images lower than 14 there you will need to backport them https://github.com/kartoza/docker-postgis/pull/343

**Comment by xqhmz** [comment]
ok,thanks
Can I use Dockerfile build postgis:11.5-2.8?
