### ISSUE TITLE
How to remove password from logs ?

### ISSUE THREAD

**Issue by abhijitgujar86** [kartoza/docker-postgis#350]
when I was starting docker i saw a line which was prominent in fact the password was written in red color. is it possible to remove it ?

` [Entrypoint] GENERATED Postgres  PASSWORD: `

**Comment by NyakudyaA** [comment]
> when I was starting docker i saw a line which was prominent in fact the password was written in red color. is it possible to remove it ?

> 
> `[Entrypoint] GENERATED Postgres PASSWORD:`

When https://github.com/kartoza/docker-postgis/pull/339 is merged, the only time the password will be printed in red is when a user runs the container without specifying the env variable
