### ISSUE TITLE
Changing TimeZone

### ISSUE THREAD

**Issue by tiqvahub** [kartoza/docker-postgis#354]
I have tried to change postgresql server timezone permanently to 'America/Sao_Paulo' by setting the variables log_timezone = 'America/Sao_Paulo' and timezone = 'America/Sao_Paulo' in the file postgis_container:/etc/postgresql/13/main/postgresql.conf. After restarting the container and postgresql, I am still getting Etc/UTC for show timezone. Is there any another way to achieve this goal? Maybe during the container build.

**Comment by NyakudyaA** [comment]
> I have tried to change postgresql server timezone permanently to 'America/Sao_Paulo' by setting the variables log_timezone = 'America/Sao_Paulo' and timezone = 'America/Sao_Paulo' in the file postgis_container:/etc/postgresql/13/main/postgresql.conf. After restarting the container and postgresql, I am still getting Etc/UTC for show timezone. Is there any another way to achieve this goal? Maybe during the container build.

https://kb.objectrocket.com/postgresql/postgresql-set-time-zone-1064

**Comment by gitlsl** [comment]
docker run  -d  -p 5432:5432 -e TZ=Asia/Shanghai -e PGTZ=Asia/Shanghai  -e TIMEZONE=Asia/Shanghai 
... 
I  try above  comand can not change default timezone?....

**Comment by xqhmz** [comment]
how to change TimeZone ? it is not a way to  achieve this goal

**Comment by NyakudyaA** [comment]
You can mount extra.conf into the container with all the timezone settings.  If the config is setup properly and it doesn't work,I suggest you reopen the issue
