### ISSUE TITLE
failed to register layer: Error processing tar file(exit status 1): symlink .. /usr/lib/llvm-7/build/Debug+Asserts: permission denied

### ISSUE THREAD

**Issue by coderLinJ5945** [kartoza/docker-postgis#355]
Hello, I would like to ask you how to resolve an exception. After uploading it to my private library at port using your Kartoza/Postgis, the above exception occurred during the pull operation. However, one of the two identical machines can pull out the image and run properly. Want to ask you how to solve? Thank you for your consideration.

# docker info
Client:
 Debug Mode: false

Server:
 Containers: 44
  Running: 25
  Paused: 0
  Stopped: 19
 Images: 206
 Server Version: 19.03.7
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.49GiB
 Name: k8s-app-node12
 ID: UMB6:OCVS:6ART:UXHO:HBPK:SWOP:N7KD:Y2JA:4ST5:L42K:4L2F:QFKN
 Docker Root Dir: /app/docker/data
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  192.168.1.171:280
  127.0.0.0/8
 Registry Mirrors:
  https://qc1g6dls.mirror.aliyuncs.com/
 Live Restore Enabled: false

# docker pull 192.168.1.171:280/kartoza/postgis:13.0
13.0: Pulling from kartoza/postgis
8559a31e96f4: Pull complete 
ef726155bc54: Pull complete 
2353d9f22e41: Pull complete 
db1183ac51d2: Pull complete 
a97ba1d016e7: Pull complete 
323e10c4fbda: Pull complete 
d029af234f1b: Pull complete 
5bb9d6338356: Pull complete 
55d75e40fd52: Extracting [==================================================>]  169.5MB/169.5MB
5731b987934b: Download complete 
317fd15a2dd6: Download complete 
68b90eb1ab02: Download complete 
22b7ce3a81ee: Download complete 
35f7f8d58c90: Download complete 
b457edfcb0f8: Download complete 
failed to register layer: Error processing tar file(exit status 1): symlink .. /usr/lib/llvm-7/build/Debug+Asserts: permission denied

# uname -a
Linux k8s-app-node5 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by NyakudyaA** [comment]
We cannot give a definite answer here with relation to private registries. I suggest you check out stack exchange.com or docker forums. 

Looking at the error message it looks like some permission error. Can you differentiate the difference between the two machines
