### ISSUE TITLE
Running in production with rootles mode

### ISSUE THREAD

**Issue by t-book** [kartoza/docker-postgis#358]
Hi,

does one have experience if this composition can be used if docker is running in rootless mode?

Thanks and best regards,

Toni

**Comment by NyakudyaA** [comment]
> Hi,
> 
> 
> 
> does one have experience if this composition can be used if docker is running in rootless mode?
> 
> 
> 
> Thanks and best regards,
> 
> 
> 
> Toni

Unfortunately this container still runs as root and you can comment on #245

**Comment by NyakudyaA** [comment]
Closing as already contains an older issue with more details
