### ISSUE TITLE
gis doesn't exist

### ISSUE THREAD

**Issue by npltr62** [kartoza/docker-postgis#359]
```
2022-01-19 13:59:08.800 UTC [240] FATAL:  database "gis" does not exist
2022-01-19 13:59:08.801 UTC [192] LOG:  background worker "pg_cron launcher" (PID 240) exited with exit code 1
```
I'm used docker-postgis and docker-backup, postgis start with variable POSTGRES_DBNAME : 'fd, restore' and docker backup use the fd database to save.
I don't understand why "pg_cron launcher" try to run on gis database whereas the target db is 'fd'

**Comment by NyakudyaA** [comment]
> ```
> 
> 2022-01-19 13:59:08.800 UTC [240] FATAL:  database "gis" does not exist
> 
> 2022-01-19 13:59:08.801 UTC [192] LOG:  background worker "pg_cron launcher" (PID 240) exited with exit code 1
> 
> ```
> 
> I'm used docker-postgis and docker-backup, postgis start with variable POSTGRES_DBNAME : 'fd, restore' and docker backup use the fd database to save.
> 
> I don't understand why "pg_cron launcher" try to run on gis database whereas the target db is 'fd'

Can you share your docker-compose that you have used
