### ISSUE TITLE
Tags in git corresponding to image tags

### ISSUE THREAD

**Issue by bjornharrtell** [kartoza/docker-postgis#362]
Fx 14-3.1 exist as image and was pushed about three months ago, but I can't find any tags for 14 the git repo. It would be useful to have those tags in git so one can know which exact source version was used.

**Comment by NyakudyaA** [comment]
> Fx 14-3.1 exist as image and was pushed about three months ago, but I can't find any tags for 14 the git repo. It would be useful to have those tags in git so one can know which exact source version was used.

We building the images using workflows https://github.com/kartoza/docker-postgis/tree/develop/.github/workflows and the version specified in the Dockerfile in the develop branch will correspond to the most recent stable PostgreSQL version

**Comment by bjornharrtell** [comment]
Ah, I see now, thanks for the explanation.
