### ISSUE TITLE
The pg_cron extension will not be used

### ISSUE THREAD

**Issue by LiHanGod** [kartoza/docker-postgis#368]
I'm running a Docker container, I want to use the pg_cron extension in this container, I did some research and it's not working, you know

This is his start order
```shell
docker run -itd --name PostgreSQL-Test -p 5433:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASS=postgres -e ALLOW_IP_RANGE=0.0.0.0/0 -e LANG=en_US.UTF-8 -e LANGUAGE=en_US:en -e LC_ALL=en_US.UTF-8 -e SHARED_PRELOAD_LIBRARIES='pg_cron' kartoza/postgis:pr-356-14-3.2
```
Once inside the container
```shell
root@ca7c66626cfa:/scripts# su - postgres
postgres@ca7c66626cfa:~$ psql           
psql (14.1 (Debian 14.1-1.pgdg110+1))
Type "help" for help.

postgres=# CREATE EXTENSION pg_cron;
ERROR:  can only create extension in database gis
DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.
HINT:  Add cron.database_name = 'postgres' in postgresql.conf to use the current database.
CONTEXT:  PL/pgSQL function inline_code_block line 4 at RAISE
postgres=# CREATE EXTENSION pg_cron;
ERROR:  can only create extension in database gis
DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.
HINT:  Add cron.database_name = 'postgres' in postgresql.conf to use the current database.
CONTEXT:  PL/pgSQL function inline_code_block line 4 at RAISE
```

Is there documentation on how to use this extension?

**Comment by NyakudyaA** [comment]
> I'm running a Docker container, I want to use the pg_cron extension in this container, I did some research and it's not working, you know
> 
> This is his start order
> 
> ```shell
> docker run -itd --name PostgreSQL-Test -p 5433:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASS=postgres -e ALLOW_IP_RANGE=0.0.0.0/0 -e LANG=en_US.UTF-8 -e LANGUAGE=en_US:en -e LC_ALL=en_US.UTF-8 -e SHARED_PRELOAD_LIBRARIES='pg_cron' kartoza/postgis:pr-356-14-3.2
> ```
> 
> Once inside the container
> 
> ```shell
> root@ca7c66626cfa:/scripts# su - postgres
> postgres@ca7c66626cfa:~$ psql           
> psql (14.1 (Debian 14.1-1.pgdg110+1))
> Type "help" for help.
> 
> postgres=# CREATE EXTENSION pg_cron;
> ERROR:  can only create extension in database gis
> DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.
> HINT:  Add cron.database_name = 'postgres' in postgresql.conf to use the current database.
> CONTEXT:  PL/pgSQL function inline_code_block line 4 at RAISE
> postgres=# CREATE EXTENSION pg_cron;
> ERROR:  can only create extension in database gis
> DETAIL:  Jobs must be scheduled from the database configured in cron.database_name, since the pg_cron background worker reads job descriptions from this database.
> HINT:  Add cron.database_name = 'postgres' in postgresql.conf to use the current database.
> CONTEXT:  PL/pgSQL function inline_code_block line 4 at RAISE
> ```
> 
> Is there documentation on how to use this extension?

The error message above is clear. It tells you that pg_cron is already activated and it can be only activated against a single database in this case the database is called `gis`.

Just run the following
```
docker run -itd --name PostgreSQL-Test -p 5433:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASS=postgres -e ALLOW_IP_RANGE=0.0.0.0/0 -e LANG=en_US.UTF-8 -e LANGUAGE=en_US:en -e LC_ALL=en_US.UTF-8 kartoza/postgis:pr-356-14-3.2
```

and inside your database you can schedule jobs against the gis database

**Comment by LiHanGod** [comment]
Can I use the PG_cron extension for other databases?

**Comment by NyakudyaA** [comment]
> Can I use the PG_cron extension for other databases?

Just specify ` -e POSTGRES_DB=mydata` and the cron will be executed against the database `mydata`

Please checkout https://github.com/citusdata/pg_cron on usage of the extentions to get more info on the capabilities

**Comment by LiHanGod** [comment]
`-e POSTGRES_DB=mydata` can specify multiple databases？
Or I create my own database and manually load the pg_cron extension

**Comment by NyakudyaA** [comment]
Please check the read me. All answers are provided
