### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by amirmallaei** [kartoza/docker-postgis#376]
I have written the following docker compose

  postgis:
    image: kartoza/postgis:9.6-2.4
    restart: always
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DBNAME=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=123456

But I cant access the DB. I get the error below:
"psql: FATAL:  Peer authentication failed for user "postgres" " while using psql -U postgres -W

**Comment by NyakudyaA** [comment]
Try 
```
su postgres
psql
```
Otherwise, connect to the database using the env variables credentials you have supplied.

**Side Note**: PostgreSQL 9.6-2.4 reached its EOL and it might be difficult for us to set up an env to debug it. We suggest migrating to a supported version

**Comment by amirmallaei** [comment]
> 
I have updated the image to latest

`  postgis:
    image: kartoza/postgis:14-3.1
    restart: always
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DBNAME=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=123456

    volumes:
      - ./postgres-data:/var/lib/postgresql/data`
     
even using su postgres did not help! 
`psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"`

**Comment by NyakudyaA** [comment]
can you please try using kartoza/postgis:14-3.2 and also using a docker volume or host mounted volume

**Comment by NyakudyaA** [comment]
This works and might be a local issue with volumes
