### ISSUE TITLE
add PL/sh language

### ISSUE THREAD

**Issue by npltr62** [kartoza/docker-postgis#378]
Do you have any tips to add PL/sh language in image?

**Comment by NyakudyaA** [comment]
https://github.com/kartoza/docker-postgis#running-sql-scripts-on-container-startup

**Comment by npltr62** [comment]
ok thanks 
the script was executed but packages wasn't installed.
docker command : docker run -d --name 'king' -v ${pwd}/plsh.sh:/docker-entrypoint-initdb.d/plsh.sh -p 5433:5432 -e POSTGRES_USER=docker -e POSTGRES_PASS=postgres -e IGNORE_INIT_HOOK_LOCKFILE=true kartoza/postgis:14-3.1
script : `#!/bin/bash
apt-get update
apt-get install -y postgresql-14-plsh && echo 'Ok'`

**Comment by NyakudyaA** [comment]
@npltr62 If you exec the container and run the script from there, `/bin/bash /docker-entrypoint-initdb.d/plsh.sh` what happens. I ran the commands manually and it works, so I assume the script should also work
