### ISSUE TITLE
Error for Postgres14 and Postgis3 Distro Focal

### ISSUE THREAD

**Issue by indeOWS** [kartoza/docker-postgis#383]
I have checked out the git develop branch and I have faced an issue while changing the Linux to:
 DISTRO=ubuntu
IMAGE_VERSION=focal
IMAGE_VARIANT=""
**The error is shown bellow after running ./build.sh**

_ERROR [internal] load metadata for docker.io/library/ubuntu:focal-            

[internal] load metadata for docker.io/library/ubuntu:focal-:
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: docker.io/library/ubuntu:focal-: not found_

**To reproduce the error**
1 - git clone https://github.com/kartoza/docker-postgis.git
2 - .env file
```
## Example environment file for docker-compose and builders

COMPOSE_PROJECT_NAME=postgis

## For build arguments
DISTRO=ubuntu
IMAGE_VERSION=focal
IMAGE_VARIANT=""
# Set GENERATE_ALL_LOCALE to empty value or 0 to build just default LOCALE: en_US.UTF-8
GENERATE_ALL_LOCALE=1
# Set the language if you need to specify LANG locale at build time
LANG=en_US.UTF-8
# locale filter to include in the locale generator
LANGS="en_US.UTF-8,id_ID.UTF-8,pt_BR.UTF-8"

POSTGRES_MAJOR_VERSION=14
POSTGIS_MAJOR_VERSION=3
POSTGIS_MINOR_RELEASE=3
BUILD_TIMESCALE=true
```
3- build.sh
```
#!/usr/bin/env bash

if [[ ! -f .env ]]; then
    echo "Default build arguments don't exists. Creating one from default value."
    cp .example.env .env
fi

docker-compose -f docker-compose.build.yml build postgis-prod

#docker-compose -f docker-compose.build-timescale.yml build postgis-prod
```

Any direction on how to solve the problem will be very appreciated.

**Comment by NyakudyaA** [comment]
You need to adjust https://github.com/kartoza/docker-postgis/blob/develop/Dockerfile#L7
to 
```
FROM $DISTRO:$IMAGE_VERSION$IMAGE_VARIANT AS postgis-base
```
