### ISSUE TITLE
add pgaudit extension

### ISSUE THREAD

**Issue by npltr62** [kartoza/docker-postgis#385]
I added pg_audit extension by a script but when i run sql cmd  "CREATE EXTENSION pgaudit;"  i had an error "pgaudit must be loaded via shared_preload_libraries' . What should i do first?

**Comment by NyakudyaA** [comment]
https://github.com/kartoza/docker-postgis#shared-preload-libraries

**Comment by npltr62** [comment]
ok but when i restart the container with "SHARED_PRELOAD_LIBRARIES='pgaudit'" i have "could not access file "pgaudit": No such file or directory"

**Comment by NyakudyaA** [comment]
You need to run the following together
```
SHARED_PRELOAD_LIBRARIES='pg_cron,pgaduti'
POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,pgaudit`
```
This will make sure that the extension gets created before we proceed to the loading of shared libraries.
