### ISSUE TITLE
Unable to connect from QGIS

### ISSUE THREAD

**Issue by instantgis** [kartoza/docker-postgis#386]
I deployed this container successfully in a VM on Oracle Cloud free tier.
I can psql it over port 5432 in a terminal in the VM ok.
I opened port 5432 in Oracle Cloud.
Yet I am unable to connect to it from QGIS and or PgAdmin4.
I am using the public IP for the VM in Oracle cloud.
The docs mention that the postgis docker container by default runs in the Docker network.
I tried --net=Host and that did not work.
How to I setup the network for this container so that I can connect to it remotely over the internet and not from the VM itself?
Thanks

**Comment by NyakudyaA** [comment]
Have you looked at the following https://www.freecodecamp.org/news/run-a-postgres-docker-container-on-oracle-cloud-infrastructure/amp/

You might need to also pass the env variable Allow_ip_range.

When you say you can't connect what error are you getting. What parameters are you using for the connection
