### ISSUE TITLE
Problem building an image with Timescale enabled

### ISSUE THREAD

**Issue by bobeal** [kartoza/docker-postgis#387]
Hello,

I was trying to build an image with Timescale enabled, using the following command:

```
docker-compose -f docker-compose.build-timescale.yml build
```

But it appeared the image built did not have the Timescale extension installed.

After some tries, I found that the problem is in the condition in https://github.com/kartoza/docker-postgis/blob/develop/Dockerfile#L108 that never matches. As a workaround, I was able to build an image with Timescale by replacing this line with:

```
RUN if [ "${BUILD_TIMESCALE}" = "true" ]; then \
```

But the case insensitive match is lost (tried many things but was not able to find an easy way to fix this).

I can submit a PR with this fix, but it would be better to still have the case insensitive match...

**Comment by NyakudyaA** [comment]
If the case insensitive match doesn't work then you can do a PR and also don't forget to add a `TODO` comment so that we can take a look at it. Also whilst you are at it you can also check the timescale version might be higher than the ones set in the Dockerfile

**Comment by bobeal** [comment]
> Also whilst you are at it you can also check the timescale version might be higher than the ones set in the Dockerfile

Indeed, I used version 2.7.2 in my image, adding this in the PR.
