### ISSUE TITLE
Tiger Geocoder

### ISSUE THREAD

**Issue by bazini627** [kartoza/docker-postgis#394]
I've got your image up and running in Podman so thank you for that.  One thing that I'm noticing that has me stuck is that there is no /var/lib/postgresql/data directory created when running this image in Podman.  I just tried using the image in Docker with persistent storage and that directory does actually get created.  Seems like there may need to be something added so that directory gets created when using this image with Podman? I was hoping I could stick the Tiger files there for the geocoder that I could then use but that doesn't seem possible right now.

**Comment by NyakudyaA** [comment]
You just need to pass the env for example: POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting, postgis_tiger_geocoder, fuzzystrmatch `
