### ISSUE TITLE
pg_cron is missing in PostgreSQL 15 image

### ISSUE THREAD

**Issue by IvanShift** [kartoza/docker-postgis#397]
Hello!
I am using the kartoza/postgis:14-3 image and want to update it to kartoza/postgis:15-3.
But pg_cron present in postgis:14-3 is missing in postgis:15-3.
Could you fix this?
Log from  kartoza/postgis:14-3 image : 

> Postgres initialisation process completed .... restarting in foreground
> 2022-12-05 08:54:49.049 UTC [213] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
> 2022-12-05 08:54:49.050 UTC [213] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> 2022-12-05 08:54:49.050 UTC [213] LOG:  listening on IPv6 address "::", port 5432
> 2022-12-05 08:54:49.051 UTC [213] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> 2022-12-05 08:54:49.054 UTC [215] LOG:  database system was shut down at 2022-12-05 08:54:48 UTC
> 2022-12-05 08:54:49.057 UTC [213] LOG:  database system is ready to accept connections
> 2022-12-05 08:54:49.061 UTC [221] LOG:  **pg_cron scheduler started**

Log from  kartoza/postgis:15-3 image : 

> 2022-12-05 08:52:26.759 UTC [222] LOG:  starting PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
> 2022-12-05 08:52:26.759 UTC [222] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> 2022-12-05 08:52:26.759 UTC [222] LOG:  listening on IPv6 address "::", port 5432
> 2022-12-05 08:52:26.761 UTC [222] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> 2022-12-05 08:52:26.764 UTC [226] LOG:  database system was shut down at 2022-12-05 08:52:25 UTC
> 2022-12-05 08:52:26.767 UTC [222] LOG:  database system is ready to accept connections

**Comment by NyakudyaA** [comment]
That's because pg-cron does not exist for PostgreSQL 15 last time I checked. Can you log in to the image and try to run 
```
apt-cache pg_cron | grep 15
```

**Comment by IvanShift** [comment]
I did this:

> root@bddcfb293ee2:/scripts# **apt-get update**
> Get:1 http://apt.postgresql.org/pub/repos/apt bullseye-pgdg InRelease [91.7 kB]
> Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
> Get:3 http://apt.postgresql.org/pub/repos/apt bullseye-pgdg/main amd64 Packages [267 kB]
> Get:4 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
> Get:5 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
> Get:6 http://deb.debian.org/debian bullseye/main amd64 Packages [8,184 kB]
> Get:7 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [208 kB]
> Get:8 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
> Fetched 8,973 kB in 2s (4,953 kB/s)                        
> Reading package lists... Done

Next:
> root@bddcfb293ee2:/scripts# **apt-get install postgresql-15-cron**
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following NEW packages will be installed:
>   postgresql-15-cron
> 0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
> Need to get 101 kB of archives.
> After this operation, 249 kB of additional disk space will be used.
> Get:1 http://apt.postgresql.org/pub/repos/apt bullseye-pgdg/main amd64 postgresql-15-cron amd64 1.4.2-2.pgdg110+1 [101 kB]
> Fetched 101 kB in 0s (316 kB/s)              
> debconf: delaying package configuration, since apt-utils is not installed
> Selecting previously unselected package postgresql-15-cron.
> (Reading database ... 30292 files and directories currently installed.)
> Preparing to unpack .../postgresql-15-cron_1.4.2-2.pgdg110+1_amd64.deb ...
> Unpacking postgresql-15-cron (1.4.2-2.pgdg110+1) ...
> Setting up postgresql-15-cron (1.4.2-2.pgdg110+1) ...
> Processing triggers for postgresql-common (246.pgdg110+1) ...
> debconf: unable to initialize frontend: Dialog
> debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
> debconf: falling back to frontend: Readline
> Building PostgreSQL dictionaries from installed myspell/hunspell packages...
> Removing obsolete dictionary files:

I suppose that pg_cron exist for  postgresql 15.

**Comment by NyakudyaA** [comment]
You are welcome to do a PR, Just uncomment out the line https://github.com/kartoza/docker-postgis/blob/develop/scripts/setup-database.sh#L113 and change https://github.com/kartoza/docker-postgis/blob/develop/scripts/env-data.sh#L282 to add the extension
