### ISSUE TITLE
Docker networks support

### ISSUE THREAD

**Issue by gcapnias** [kartoza/docker-postgis#40]
I am trying to use "docker-postgis" image within a Docker network.

The default Docker network is 172.17.0.0/16. Although, if a Docker network is used, the IPs change range to 172.18.0.0/16 for the first network, 172.19.0.0/16 for the second, etc.

Would it be possible to add support for Docker networking, not for the default network only - perhaps change 172.17.0.0/16 to 172.0.0.0/24?

Ref: Docker - Work with network commands (https://docs.docker.com/engine/userguide/networking/work-with-networks/)

**Comment by matt-baker** [comment]
Docker machine is using [192.168.0.0/16 ](https://docs.docker.com/machine/reference/ip/). Adding support for docker machine would also be great.

Just in case it's useful for anyone else who is unable to connect over docker machine, a quick workaround to have Postgresql listen for all connections is:
```
# Create container and attach to it
docker pull kartoza/postgis
docker run --name "postgis" -p 25432:5432 -d -t kartoza/postgis
docker exec -it postgis bash

# Update pg_hba.conf and exit
echo "host    all             all             192.168.0.0/16              md5" >> /etc/postgresql/9.4/main/pg_hba.conf
echo "listen_addresses = '*'" >> /etc/postgresql/9.4/main/postgresql.conf
echo "port = 5432" >> /etc/postgresql/9.4/main/postgresql.conf
exit

# Restart container
docker restart postgis
```
Other than this minor issue, this image has been very useful. Thanks @kartoza!

**Comment by mbernasocchi** [comment]
@timlinux what do you think about this? I've been successful with
```environment: 
      - ALLOW_IP_RANGE=172.20.0.0/16
```

in a docker-compose v2 but this is obviously going to break if my network is not exactly a 172.20 subnet.

**Comment by NyakudyaA** [comment]
This has been solved
