### ISSUE TITLE
Document the kartoza/postgis:15-3.3-timescale container image

### ISSUE THREAD

**Issue by lewismc** [kartoza/docker-postgis#413]
### Feature description

Hi folks, I recently noticed the [kartoza/postgis:15-3.3-timescale](https://hub.docker.com/layers/kartoza/postgis/15-3.3-timescale/images/sha256-9d3d71bac69e3812d0bf340b4df1ac45f091e04df55f87e9124931e99dbd0b30?context=explore) and I am very keen to use it. I wanted to learn more but couldn't find dedicated documentation. If someone could brief me on the container characteristics and how the Timescale extension can be configured then I would be happy to provide a documentation PR. Thanks in advance for your consideration.

**Comment by NyakudyaA** [comment]
You can build the images locally  using https://github.com/kartoza/docker-postgis/blob/develop/docker-compose.build-timescale.yml where the env variable in https://github.com/kartoza/docker-postgis/blob/develop/.example.env need to be
`BUILD_TIMESCALE=true`

for using the image the same parameters for this image are useful, you will need to pass the following env variable
```
 POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,timescaledb,pg_cron
 ACCEPT_TIMESCALE_TUNING=TRUE
```
