### ISSUE TITLE
Version upgrade workflow

### ISSUE THREAD

**Issue by rumski20** [kartoza/docker-postgis#415]
### Feature description

I am looking for a way to upgrade my container's version from 9.6-2.4 to the current version (15?-3?). Do you have a workflow that you can recommend for accomplishing this? (Or, even better, a script for handling this?)

Thank you!

**Comment by NyakudyaA** [comment]
I think this is more suited for stack exchange. https://letmegooglethat.com/?q=How+to+upgrade+postgresql+from+9.6+to+15+in+docker
