### ISSUE TITLE
Host mounted volumes fails to chown directory

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/docker-postgis#418]
### What is the bug or the crash?

```
docker run --name "postgis" -v `pwd`/data:/var/lib/postgresql -p 25432:5432  -it kartoza/postgis:15-3.3
```

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/2510900/228195093-b3d8fe6e-dc8a-4983-b723-c485b71158da.png)

### Versions

kartoza/postgis:15-3.3

**Comment by lewismc** [comment]
Yes I also noticed this issue. 
@renato2099 FYI
I worked around by manually changing the permissions of the host mount directories...

**Comment by renato2099** [comment]
yes indeed @lewismc , this seems like what I have been observing as well, I thought it was related to the fact that the docker directory was already created which was causing issues at mounting time, but yeah it seems like it is not :)

@NyakudyaA is there a way we could test your fix in an easy way? maybe you could share with us some pointers please?

**Comment by NyakudyaA** [comment]
@renato2099 @lewismc Can you please try using `kartoza/postgis:pr-419-15-3.3` to test? I hope it's the correct image name and I have also added a scenario test for future foolproofing. Will merge after your tests
