### ISSUE TITLE
postgres_data in a file system with no ownership: docker idling

### ISSUE THREAD

**Issue by guizar** [kartoza/docker-postgis#427]
### What is the bug or the crash?

Hi,

I'm trying to create a container where the volume points to a disk with no ownership. This seems to be preventing the container from starting (it's stuck in a restarting state):

```
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS                          PORTS      NAMES
da2b0b620f7f   kartoza/postgis:12.0       "/bin/sh -c /docker-…"   41 seconds ago   Restarting (1) 10 seconds ago              postgis
```

When I initiate the container pointing to a folder with standard ownership system docker works as expected.

Any hint on how to bypass this issue?

The command that I'm using to start the container is:

```
docker run --name=postgis -d -e POSTGRES_USER=XXX -e POSTGRES_PASS=XXX -e POSTGRES_DBNAME=DDD -e ALLOW_IP_RANGE=0.0.0.0/0 -p 5434:5432 -v /maps-priv/maps/XXX/postgres_data:/var/lib/postgresql --restart=always kartoza/postgis:12.0
```

Thanks!

### Steps to reproduce the issue

```
docker run --name=postgis -d -e POSTGRES_USER=XXX -e POSTGRES_PASS=XXX -e POSTGRES_DBNAME=DDD -e ALLOW_IP_RANGE=0.0.0.0/0 -p 5434:5432 -v /maps-priv/maps/XXX/postgres_data:/var/lib/postgresql --restart=always kartoza/postgis:12.0
```

where `-v` points to a volume where files have no ownership

### Versions

12.0

**Comment by NyakudyaA** [comment]
please try the latest image, a lot of changes have been merged since 12 was last updated
