### ISSUE TITLE
docker-compose commands not running the consistent 25432 port

### ISSUE THREAD

**Issue by mbforr** [kartoza/docker-postgis#434]
### What is the bug or the crash?

After using the out of the box docker-compose method it starts a different proxy port every time. I was able to fix this by modifying this line to 25432:5432

https://github.com/kartoza/docker-postgis/blob/develop/docker-compose.yml#L24

### Steps to reproduce the issue

1. Pull the repo via GitHub
2. Start the container with `docker-compose up -d`

### Versions

kartoza/postgis:15-3.3

**Comment by NyakudyaA** [comment]
That's not a bug, if you don't specify a port like the way it is, it will randomly choose a port. We either need to update the documentation to reflect this or add the 25432 port back. Can you handle putting the 25432 port in the compose file as a PR

**Comment by mbforr** [comment]
Just added it here - #437
