### ISSUE TITLE
add configuration tweaks

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-postgis#44]
There are several tweaks to optimise PostgreSQL performance for spatial, mostly in postgresql.conf. 

Include these as defaults in this setup
- [x] increase shared_buffers from default to 500MB (in postgresql.conf)
  - you also need to add these lines to the end of  /etc/sysctl.conf. 
    `kernel.shmmax=543252480`
    `kernel.shmall=2097152`
  - shmall units are pages and shmmax units are bytes(?) equivalent to the desired shared_buffer size - in this case 500MB
  - to see page size so you can calculate number of pages for shmall:

```
python
>>> import resource
>>> resource.getpagesize()
4096
```
- [x] change work_mem from default to 16MB
- [x] change maintenance_work_mem from  default to 128MB
- [x] change wal_buffers from default to 1MB
- [x] change checkpoint_segments from 3 to 6 
  - only if PostgreSQL <= 9.4
- [x] change random_page_cost from default to 2
- [x] set xmloption = 'document' 
  - so QGIS QML docs can be stored in layer_styles

**Comment by gubuntu** [comment]
Hopefully resolved with #92

**Comment by NyakudyaA** [comment]
All these tweaks are now standard in all images
