### ISSUE TITLE
Support for shp2pgsql and pgsql2shp?

### ISSUE THREAD

**Issue by matt-baker** [kartoza/docker-postgis#46]
Hi,

Are there any plans or interest to add support for the [shp2pgsql](http://postgis.net/docs/manual-1.3/ch04.html#id435762) and [phsql2shp](http://postgis.net/docs/manual-1.3/ch04.html#id436110) utilities? 

Being able to quickly and easily import/export data using these is useful for those of us who are required to dabble in the world of shapefiles occasionally. 

I was able to get something working by mounting a volume and installing postgis (I assume the utilities are not part of the postgresql-9.4-postgis-2.1 specified in the Dockerfile) so there is a workaround. I suspect there is a cleaner way to do this though.

```
# The workaround

# Start the container and mount /gisdata volume using -v
docker run --name "postgis" -v /gisdata:/gisdata  -p 25432:5432 -d -t kartoza/postgis

# Attach to running container
docker exec -i -t postgis /bin/bash

# Install postgis
apt-get install postgis

# Install vim, edit pg_hba.conf, and reload postgres
apt-get install vim-nox
vi /etc/postgresql/9.5/main/pg_hba.conf 
# local  all      all          peer
local  all      all          md5
service postgresql reload # FYI - restart will kill the container

# Export data to /gisdata
pgsql2shp -u docker -P docker -f /gisdata/test.shp database table
```

Thanks,

Matt

**Comment by kofronpi** [comment]
@matt-baker couldn't you create another container with the postgis utilites and use it from there ? I use shp2pgsql from my main os into this docker-postgis image with success.

**Comment by matt-baker** [comment]
@kofronpi - great idea. Thanks.

**Comment by tonychen0716** [comment]
@kofronpi how to install shp2pgsql on my macOS,  thanks

**Comment by kofronpi** [comment]
@tonychen0716  I don't know, I was using ubuntu at the time ?

**Comment by NyakudyaA** [comment]
> @kofronpi how to install shp2pgsql on my macOS, thanks

I think this is all part of postgis installation. Depends if you installing with homebrew or enterprise DB
