### ISSUE TITLE
Can't connect to the container from host

### ISSUE THREAD

**Issue by andpash** [kartoza/docker-postgis#469]
### What is the bug or the crash?

Can't connect to new version of the container from host,
but everything ОК to the old version.
The same situation when using `localhost` or `host_ip`.

### Steps to reproduce the issue

docker run -d -t --name "postgis7"  -p 5437:5432 kartoza/postgis:16-3.4--v2023.11.04

psql -h localhost -p 5437 -U docker gis
psql: error: connection to server at "localhost" (127.0.0.1), port 5437 failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
####
docker run -d -t  --name "postgis8"  -p 5438:5432 kartoza/postgis:pr-356-14-3.2
psql -h localhost -p 5438 -U docker gis                 
Password for user docker:

### Versions

new version of PostgreSQL: 16
old version of PostgreSQL: 14

**Comment by spatialgeobyte** [comment]
@andpash I cannot replicate using the same instructions you have provided. Maybe check the logs of the container and let us know, closing for now. Reopen if issue persist or is reproducible
