### ISSUE TITLE
After start script

### ISSUE THREAD

**Issue by davidbarton** [kartoza/docker-postgis#47]
Hello, how do I run script/command after container is up and running? I am thinking something like this

```
#!/bin/bash

# Allowing incoming connections out of docker
echo "host all all 0.0.0.0/0 md5" >> /etc/postgresql/9.4/main/pg_hba.conf

# Run container command
/start-postgis.sh

# Create database with tables if not exist
psql -tc "SELECT 1 FROM pg_database WHERE datname = 'czechnu'" | grep -q 1 || psql postgres -f /var/pg_schema/db_czechnu.sql
```

**Comment by timlinux** [comment]
@davidbarton you have basically two choices:

1) Derive your own container using mine as a base and modify the startup script
2) do it in bash, spinning up an instance  of postgis and then executing your script.

As for your script - you can provide  additional ip ranges to allow as a start env variable (consult the README for details).
