### ISSUE TITLE
Tweak shared_buffers and work_mem

### ISSUE THREAD

**Issue by Guz-TsTech** [kartoza/docker-postgis#471]
### Tweak of shared_buffers and work_mem

Hi,

I need to tweak shared_buffers ans work_mem as I want PostgreSQL to use more RAM as my server got 128 GB RAM.

How can I achieve that ? I tried to set env variables with no success.

Regards.

**Comment by NyakudyaA** [comment]
https://github.com/kartoza/docker-postgis?tab=readme-ov-file#additional-configuration
