### ISSUE TITLE
Can't make connection with container when detached

### ISSUE THREAD

**Issue by jjcfrancisco** [kartoza/docker-postgis#474]
### What is the bug or the crash?

A connection cannot be made with the container when in detached mode

### Steps to reproduce the issue
**Can't** make connection ❌
```bash
docker run --name "my-db" \
    -p 25432:5432 \
    -e POSTGRES_USER=my_user \
    -e POSTGRES_PASS=my_password \
    -e POSTGRES_DBNAME=my_database \
    -d -t kartoza/postgis:16-3.4
```

**Can** make connection ✅
```bash
docker run --name "my-db" \
    -p 25432:5432 \
    -e POSTGRES_USER=my_user \
    -e POSTGRES_PASS=my_password \
    -e POSTGRES_DBNAME=my_database \
    -t kartoza/postgis:16-3.4
```

### Versions

kartoza/postgis:16-3.4

### Additional context

1. It is possible to make a connection internally via `docker exec` -> `psql`.
2. Using the arm64 build.

**Comment by timlinux** [comment]
Can you clarify the test you are doing for making a connection? It works fine for me here:

![image](https://github.com/kartoza/docker-postgis/assets/178003/da19b873-ac6d-469e-8039-3be934db1c04)


![image](https://github.com/kartoza/docker-postgis/assets/178003/5a6e0bfc-dc41-4964-8211-17fdae01cb2b)
