### ISSUE TITLE
Add plperl extension

### ISSUE THREAD

**Issue by sgaunet** [kartoza/docker-postgis#478]
### Feature description

Hello,

I'm interested by the plperl extension. Is there a way to add it ?

**Comment by NyakudyaA** [comment]
Have you tried? 
```
CREATE EXTENSION plperl
```

**Comment by sgaunet** [comment]
I have tested, it's not working with the last stable version: 16-3.4--v2024.03.17

Here is the log:

```
postgis-db-1  | 2024-07-23 06:29:34.493 UTC [225] docker@gis ERROR:  extension "plperl" is not available
postgis-db-1  | 2024-07-23 06:29:34.493 UTC [225] docker@gis DETAIL:  Could not open extension control file "/usr/share/postgresql/16/extension/plperl.control": No such file or directory.
postgis-db-1  | 2024-07-23 06:29:34.493 UTC [225] docker@gis HINT:  The extension must first be installed on the system where PostgreSQL is running.
```

**Comment by NyakudyaA** [comment]
You will need to install additional packages needed for the extension. Please check the documentation for that extension and if you find the packages there are various ways to extend this image

* build a new image using this as the base
* run the entry point bash script to install additional packages

**Comment by sgaunet** [comment]
I've done what I wanted to achieve. In fact, it was really simple. I've just make my own docker image based on your image:

```
FROM kartoza/postgis:17-3.5
RUN apt-get update -y && apt-get install -y postgresql-plperl-17
```

That's all. If anyone is interested, I've made a repository: https://github.com/sgaunet/postgis

Thanks for your work :)

**Comment by NyakudyaA** [comment]
> I've done what I wanted to achieve. In fact, it was really simple. I've just make my own docker image based on your image:
> 
> ```
> FROM kartoza/postgis:17-3.5
> RUN apt-get update -y && apt-get install -y postgresql-plperl-17
> ```
> 
> That's all. If anyone is interested, I've made a repository: https://github.com/sgaunet/postgis
> 
> Thanks for your work :)

Maybe you can do a pull request so that we can add this to the image and publish

**Comment by sgaunet** [comment]
PR done :)

https://github.com/kartoza/docker-postgis/pull/493
