### ISSUE TITLE
Confusing instructions and unable to connect

### ISSUE THREAD

**Issue by culebron** [kartoza/docker-postgis#53]
So, I read the README.md, and there's this line

    sudo docker run --name "postgis" -p 25432:5432 -d -t kartoza/postgis

And then below there's another subsection called "Convenience run script"

    ./run-postgis-docker.sh (some parameters)
    and then run
    psql -h localhost -U docker -p 25432 -l

I open this script in an editor, and there's no section `-p 25432:5432`, so you should connect to 5432 instead. This has to be fixed.

I decided to stick with the scripts, just to keep things saved in files. I did

    ./run-postgis-docker.sh -v tst -n postgis1 -u culebron -p culebron

It should have created a role `culebron` with password `culebron`. I try to connect:

    psql -l -p 5432 -h localhost -U culebron

And get this error:

    Password for user culebron: 
    psql: FATAL:  password authentication failed for user "culebron"
    FATAL:  password authentication failed for user "culebron"

Did not touch anything. Inside the container, it works fine.

What am I doing wrong?

**Comment by culebron** [comment]
Found out the problem source:

The convenience script has no `-p` parameter, so the port is just not available, but I have another instance of Postgres running in that machine, and it accepted connection to 5432, and was rejecting my user/password.

Need to add `-p 25432:5432` to `run-postgis-docker.sh`.

**Comment by timlinux** [comment]
I updated ``run-postgis-docker.sh`` now thanks
