### ISSUE TITLE
Errors on restart

### ISSUE THREAD

**Issue by AndreLobato** [kartoza/docker-postgis#56]
Hi There, I am getting some errors when starting or restarting the image. I am wondering if those could indicate a issue in the termination process and if this could lead to a future corruption, in case I deploy this image in production...

So when I first start the `latest` image (currently 9.5.6) with...
```docker run -ti kartoza/postgis```

I get...
```
...
CREATE EXTENSION
Loading legacy sql
/usr/share/postgresql/9.5/contrib/postgis-2.2/legacy_minimal.sql: No such file or directory
/usr/share/postgresql/9.5/contrib/postgis-2.2/legacy_gist.sql: No such file or directory
...
Postgres initialisation process completed .... restarting in foreground
2017-03-26 20:59:01.168 UTC [153] LOG:  database system was interrupted; last known up at 2017-03-26 20:59:00 UTC
2017-03-26 20:59:15.668 UTC [153] LOG:  database system was not properly shut down; automatic recovery in progress
2017-03-26 20:59:15.687 UTC [153] LOG:  redo starts at 0/1F1BA90
2017-03-26 20:59:15.687 UTC [153] LOG:  invalid record length at 0/1F1BAB8
2017-03-26 20:59:15.687 UTC [153] LOG:  redo done at 0/1F1BA90
```
I also get those errors every time it restarts. Any ideas?

**Comment by timlinux** [comment]
Perhaps those scripts have been removed from postgis 2.2 - I am going to check on that quickly...

**Comment by AndreLobato** [comment]
Actually I was more concerned with the proper termination of the background process, which was preventing the image to start at all on Centos 7. So I did this PR to help to prevent this. There is still the proper termination of the foreground process that needs improvement as well, because at the moment, it hangs on the primary docker TERM signal and only exits on KILL, not gracefully terminating.

**Comment by timlinux** [comment]
Ok thanks for the clarification. The legacy scripts referenced in this issue are probably a red herring - they provided backwards compatibility support for Postgis 1.5 users migrating to 2.x. It seems the scripts have since been removed. I am making a PR to remove them from the startup script - then we can close this issue out and address the underlying issue you describe here separately.

**Comment by timlinux** [comment]
See https://github.com/kartoza/docker-postgis/pull/59

**Comment by timlinux** [comment]
Closing this as it should be taken care of in #59 - please re-open if troubles persist.
