### ISSUE TITLE
WIll data persist if docker is shut down?

### ISSUE THREAD

**Issue by kodeine** [kartoza/docker-postgis#64]
I wanted to know if databases will persist when docker shutsdown?

**Comment by blackjackyau** [comment]
it will not persist if "docker-compose down", as the data follows the container (docker-compose stop) will not kill the data on the next docker-compose start
Always encourage to mount the data folder (/var/lib/postgresql) to the host file system

**Comment by timlinux** [comment]
This is covered in the readme here:

https://github.com/kartoza/docker-postgis#storing-data-on-the-host-rather-than-the-container
