### ISSUE TITLE
Ive got an issue when i run python manage.py runserver 0.0.0.0:8000  i get this long error. Someone please help

### ISSUE THREAD

**Issue by NicholasDsouza1996** [kartoza/docker-postgis#69]
![error1](https://user-images.githubusercontent.com/20857536/30002477-07c1e95c-909a-11e7-8377-ca9ed9f05978.png)
![error2](https://user-images.githubusercontent.com/20857536/30002478-0914af9c-909a-11e7-8fe6-8d9e257af577.png)
![error3](https://user-images.githubusercontent.com/20857536/30002480-0a84faa8-909a-11e7-92a5-356190f323e9.png)

**Comment by timlinux** [comment]
I'm sorry but your error seems to relate to your django project not to docker-postgis. Can you please ask your questions over on geonode? Thanks!
