### ISSUE TITLE
error in command-line parsing in run-postgis-docker.sh

### ISSUE THREAD

**Issue by lwiechec** [kartoza/docker-postgis#72]
I think there is a typo in https://github.com/kartoza/docker-postgis/blob/develop/run-postgis-docker.sh#L43; should it not be `d)` ?

**Comment by timlinux** [comment]
Its fixed in master but it seem there is still a problem with the script since it always only shows the help text.

**Comment by NyakudyaA** [comment]
This has been replaced by docker-compose
