### ISSUE TITLE
Default user is not as per readme

### ISSUE THREAD

**Issue by anentropic** [kartoza/docker-postgis#8]
"If these are not specified then the postgresql user is set to 'docker' with password 'docker'."

this is failing somehow... if I look in the `/tmp/PGPASSWORD.txt` file that was created by the startup script I see:

```
postgresql user: postgres
postgresql password: docker
```

hmm... and in the logs when running my image:

```
postgres_1 | 2014-12-05 04:15:56 UTC ERROR:  role "postgres" already exists
postgres_1 | 2014-12-05 04:15:56 UTC STATEMENT:  CREATE USER postgres WITH SUPERUSER ENCRYPTED PASSWORD 'docker';
```

which leaves me where I am, i.e. intended `docker` user was not created and `postgres` user has an unknown password

**Comment by timlinux** [comment]
This should be fixed with your PR applied from #14 - thanks. Note that the hub image is still not building - there seems to be some issue on hub itself since the builds are working here locally. I am going to close out this issue for now. Thanks!
