### ISSUE TITLE
Can't log into the database

### ISSUE THREAD

**Issue by Jyrks** [kartoza/docker-postgis#80]
I started a docker container: docker run --name "postgis" -p 5432:5432 -d -t kartoza/postgis:9.6-2.4

When I try to log in using bash it fails with user docker and password docker:
docker exec -it postgis bash
root@23bc932b6063:/# psql -U docker
psql: FATAL:  Peer authentication failed for user "docker"

**Comment by NyakudyaA** [comment]
@Jyrks The default database that is created when starting the container is called gis. You need to connect to this database
 ` psql -U docker -p 5432 -h localhost -d gis`
